import { writeFileSync } from "node:fs";
import {
  dogs,
  exposureItems,
  healthEvents,
  journalEntries,
  milestones,
  people,
  relationshipLogs,
  todayTasks,
} from "../src/data";

const HOUSEHOLD_ID = "11111111-1111-1111-1111-111111111111";
const PERSON_IDS: Record<string, string> = {
  andrew: "11111111-1111-1111-1111-111111111112",
  bree: "11111111-1111-1111-1111-111111111113",
};
const DOG_IDS: Record<string, string> = {
  puppy: "11111111-1111-1111-1111-111111111114",
  griz: "11111111-1111-1111-1111-111111111115",
};

function str(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function num(value: number | null | undefined): string {
  return value === null || value === undefined ? "NULL" : String(value);
}

function bool(value: boolean): string {
  return value ? "true" : "false";
}

function textArray(values: string[]): string {
  return `ARRAY[${values.map((v) => str(v)).join(", ")}]::text[]`;
}

function uuidArray(values: string[]): string {
  return `ARRAY[${values.map((v) => str(v)).join(", ")}]::uuid[]`;
}

function jsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function dogRef(id: string): string {
  const mapped = DOG_IDS[id];
  if (!mapped) throw new Error(`Unknown dog id in seed data: ${id}`);
  return mapped;
}

function personRef(id: string): string {
  const mapped = PERSON_IDS[id];
  if (!mapped) throw new Error(`Unknown person id in seed data: ${id}`);
  return mapped;
}

const lines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts from src/data.ts. Do not hand-edit — regenerate instead.",
  "-- Run once in the Supabase SQL Editor, after schema.sql, to seed the app with its starting content.",
  "",
  `insert into households (id, name) values (${str(HOUSEHOLD_ID)}, ${str("Andrew & Bree's household")})`,
  "on conflict (id) do nothing;",
  "",
];

for (const person of people) {
  lines.push(
    `insert into people (id, household_id, name, color) values (${str(personRef(person.id))}, ${str(HOUSEHOLD_ID)}, ${str(person.name)}, ${str(person.color)})`,
    "on conflict (id) do nothing;",
  );
}
lines.push("");

for (const dog of dogs) {
  lines.push(
    `insert into dogs (id, household_id, name, breed, birthday, sex, color, weight, expected_adult_weight, weight_history, microchip, photo, veterinarian, insurance, breeder, health_summary, medical_history, allergies, medications, energy, confidence, fearfulness, resource_guarding, dog_friendliness, human_friendliness, noise_sensitivity, favorite_rewards, favorite_toys, mastered_commands, exercise_need, status) values (`,
    `  ${str(dogRef(dog.id))}, ${str(HOUSEHOLD_ID)}, ${str(dog.name)}, ${str(dog.breed)}, ${str(dog.birthday)}, ${str(dog.sex)}, ${str(dog.color)},`,
    `  ${num(dog.weight)}, ${num(dog.expectedAdultWeight)}, ${jsonb(dog.weightHistory)}, ${str(dog.microchip)}, ${str(dog.photo)}, ${str(dog.veterinarian)}, ${str(dog.insurance)}, ${str(dog.breeder)}, ${str(dog.healthSummary)},`,
    `  ${textArray(dog.medicalHistory)}, ${textArray(dog.allergies)}, ${textArray(dog.medications)},`,
    `  ${num(dog.energy)}, ${num(dog.confidence)}, ${num(dog.fearfulness)}, ${num(dog.resourceGuarding)}, ${num(dog.dogFriendliness)}, ${num(dog.humanFriendliness)}, ${num(dog.noiseSensitivity)},`,
    `  ${textArray(dog.favoriteRewards)}, ${textArray(dog.favoriteToys)}, ${textArray(dog.masteredCommands)}, ${str(dog.exerciseNeed)}, ${str(dog.status)}`,
    ") on conflict (id) do nothing;",
    "",
  );
}

for (const task of todayTasks) {
  lines.push(
    `insert into tasks (household_id, title, category, assigned_to, time, duration, priority, supplies, setting, difficulty, dog_ids, checklist, griz_participation, notes) values (`,
    `  ${str(HOUSEHOLD_ID)}, ${str(task.title)}, ${str(task.category)}, ${str(personRef(task.assignedTo))}, ${str(task.time)}, ${num(task.duration)}, ${str(task.priority)}, ${textArray(task.supplies)}, ${str(task.setting)}, ${num(task.difficulty)}, ${uuidArray(task.dogIds.map(dogRef))}, ${textArray(task.checklist)}, ${str(task.grizParticipation)}, ${str(task.notes)}`,
    ");",
    "",
  );
}

for (const milestone of milestones) {
  lines.push(
    `insert into milestones (id, household_id, title, track, status, dependencies, age_gate_weeks, dog_ids, steps, sources, why) values (`,
    `  ${str(milestone.id)}, ${str(HOUSEHOLD_ID)}, ${str(milestone.title)}, ${str(milestone.track)}, ${str(milestone.status)}, ${textArray(milestone.dependencies)}, ${num(milestone.ageGateWeeks ?? null)},`,
    `  ${uuidArray(milestone.dogIds.map(dogRef))}, ${jsonb(milestone.steps)}, ${jsonb(milestone.sources)}, ${str(milestone.why)}`,
    ") on conflict (id) do nothing;",
    "",
  );
}

for (const event of healthEvents) {
  lines.push(
    `insert into health_events (household_id, dog_id, title, date, kind, notes) values (${str(HOUSEHOLD_ID)}, ${str(dogRef(event.dogId))}, ${str(event.title)}, ${str(event.date)}, ${str(event.kind)}, ${str(event.notes)});`,
  );
}
lines.push("");

for (const entry of journalEntries) {
  lines.push(
    `insert into journal_entries (household_id, dog_ids, date, title, text, tags, mood) values (${str(HOUSEHOLD_ID)}, ${uuidArray(entry.dogIds.map(dogRef))}, ${str(entry.date)}, ${str(entry.title)}, ${str(entry.text)}, ${textArray(entry.tags)}, ${str(entry.mood)});`,
  );
}
lines.push("");

for (const item of exposureItems) {
  lines.push(
    `insert into exposure_items (id, household_id, category, title, dog_ids, status, log) values (${str(item.id)}, ${str(HOUSEHOLD_ID)}, ${str(item.category)}, ${str(item.title)}, ${uuidArray(item.dogIds.map(dogRef))}, ${str(item.status)}, ${jsonb(item.log)})`,
    "on conflict (id) do nothing;",
  );
}
lines.push("");

for (const log of relationshipLogs) {
  lines.push(
    `insert into relationship_logs (household_id, dog_ids, date, comfort, shared_toys, shared_beds, shared_walks, body_language, resource_guarding, play_quality, corrections, recovery_minutes, notes) values (`,
    `  ${str(HOUSEHOLD_ID)}, ${uuidArray(log.dogIds.map(dogRef))}, ${str(log.date)}, ${num(log.comfort)}, ${num(log.sharedToys)}, ${num(log.sharedBeds)}, ${num(log.sharedWalks)}, ${num(log.bodyLanguage)}, ${num(log.resourceGuarding)}, ${num(log.playQuality)}, ${num(log.corrections)}, ${num(log.recoveryMinutes)}, ${str(log.notes)}`,
    ");",
  );
}

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${lines.length} lines)`);
