import { writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import {
  aloneTimeLogs,
  dogs,
  exposureItems,
  items,
  journalEntries,
  milestones,
  people,
  relationshipLogs,
} from "../src/data";

const HOUSEHOLD_ID = "11111111-1111-1111-1111-111111111111";
const PERSON_IDS: Record<string, string> = {
  andrew: "11111111-1111-1111-1111-111111111112",
  bree: "11111111-1111-1111-1111-111111111113",
};
const DOG_IDS: Record<string, string> = {
  puppy: "11111111-1111-1111-1111-111111111114",
  griz: "11111111-1111-1111-1111-111111111115",
};

function str(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function num(value: number | null | undefined): string {
  return value === null || value === undefined ? "NULL" : String(value);
}

function textArray(values: string[]): string {
  return `ARRAY[${values.map((v) => str(v)).join(", ")}]::text[]`;
}

function uuidArray(values: string[]): string {
  return `ARRAY[${values.map((v) => str(v)).join(", ")}]::uuid[]`;
}

function dateArray(values: string[]): string {
  return `ARRAY[${values.map((v) => str(v)).join(", ")}]::date[]`;
}

function jsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function dogRef(id: string): string {
  const mapped = DOG_IDS[id];
  if (!mapped) throw new Error(`Unknown dog id in seed data: ${id}`);
  return mapped;
}

function personRef(id: string): string {
  const mapped = PERSON_IDS[id];
  if (!mapped) throw new Error(`Unknown person id in seed data: ${id}`);
  return mapped;
}

// people/dogs/milestones/exposure_items keep stable ids across regenerations,
// so re-running this script can safely UPDATE them in place — no risk to
// anything that references them by id (tasks.assigned_to, health_events.dog_id, etc).
function upsertClause(columns: string[]): string {
  return `on conflict (id) do update set ${columns.map((c) => `${c} = excluded.${c}`).join(", ")};`;
}

// health_events/journal_entries/relationship_logs/calendar_events/alone_time_logs
// have no natural key that's safe to upsert on — real user entries (quick-log,
// journal, relationship tracker) can legitimately share a title+date, so a
// content-based unique constraint would block real future inserts. Instead we
// assign each seed row a fixed, deterministic id (stable across regenerations
// as long as array order in src/data.ts doesn't change) and upsert on that id,
// same pattern as milestones/exposure_items but computed rather than hand-authored.
function seedId(table: string, index: number): string {
  const hash = createHash("sha1").update(`dog-life-seed:${table}:${index}`).digest("hex");
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    `5${hash.slice(13, 16)}`,
    `${((parseInt(hash[16], 16) & 0x3) | 0x8).toString(16)}${hash.slice(17, 20)}`,
    hash.slice(20, 32),
  ].join("-");
}

const lines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts from src/data.ts. Do not hand-edit — regenerate instead.",
  "-- Run in the Supabase SQL Editor, after schema.sql, to seed or refresh the app's starting content.",
  "--",
  "-- Safe to re-run: households/people/dogs/milestones/exposure_items are UPSERTED in place by",
  "-- stable id, so re-running just refreshes their fields (breed, sources, dependencies, etc.)",
  "-- without touching anything that references them.",
  "--",
  "-- CAVEAT: milestones/exposure_items upsert also overwrites `status`/`steps`/`log` with the",
  "-- seed defaults (unstarted). If you've already logged real training progress in the app,",
  "-- re-running this will reset that progress back to zero. Safe right now since the puppy",
  "-- isn't picked up yet (nothing real has been logged), but don't blindly re-run this later.",
  "--",
  "-- `tasks` is now UPSERTED too, on (household_id, title) — see the unique constraint added",
  "-- 2026-07-16 in schema.sql. This is what fixed the 'same task duplicated 5+ times on the",
  "-- calendar' bug: every earlier re-run of this file had inserted a fresh duplicate of every",
  "-- task with no conflict handling at all. If you're seeing duplicates from before this fix,",
  "-- run supabase/dedupe-tasks-2026-07-16.sql once, first.",
  "--",
  "-- health_events/journal_entries/relationship_logs/calendar_events/alone_time_logs are now",
  "-- UPSERTED too, on a fixed deterministic id (see seedId() above) rather than a content-based",
  "-- key, since those tables also accept real user-entered rows (quick-log, journal, relationship",
  "-- tracker) that can legitimately repeat a title+date. If you're seeing duplicates from before",
  "-- this fix, run supabase/dedupe-remaining-tables-2026-07-22.sql once, first — it wipes only",
  "-- the seed-originated rows in these 5 tables, safe only because this household hadn't logged",
  "-- any real entries there yet as of 2026-07-22.",
  "--",
  "-- calendar_events changed shape 2026-07-23 (day_of_week/active_from/active_to/time_label/",
  "-- coverage_needed -> recurrence/excluded_dates/start_time/end_time/alone_time_required), and",
  "-- task/calendar-event categories were unified (old \"care\" tasks split into potty/meals). If",
  "-- you're running this against a database from before 2026-07-23, run",
  "-- supabase/migrate-calendar-events-2026-07-23.sql once, first — it backfills the new columns",
  "-- from the old ones and drops the old ones, which this file's UPSERTs now assume are gone.",
  "",
  `insert into households (id, name) values (${str(HOUSEHOLD_ID)}, ${str("Andrew & Bree's household")})`,
  "on conflict (id) do nothing;",
  "",
];

for (const person of people) {
  lines.push(
    `insert into people (id, household_id, name, color) values (${str(personRef(person.id))}, ${str(HOUSEHOLD_ID)}, ${str(person.name)}, ${str(person.color)})`,
    upsertClause(["name", "color"]),
  );
}
lines.push("");

for (const dog of dogs) {
  lines.push(
    `insert into dogs (id, household_id, name, breed, birthday, sex, color, weight, expected_adult_weight, weight_history, microchip, photo, veterinarian, insurance, breeder, health_summary, medical_history, allergies, medication_entries, energy, confidence, fearfulness, resource_guarding, dog_friendliness, human_friendliness, noise_sensitivity, favorite_rewards, favorite_toys, mastered_commands, exercise_need, status) values (`,
    `  ${str(dogRef(dog.id))}, ${str(HOUSEHOLD_ID)}, ${str(dog.name)}, ${str(dog.breed)}, ${dog.birthday ? str(dog.birthday) : "NULL"}, ${str(dog.sex)}, ${str(dog.color)},`,
    `  ${num(dog.weight)}, ${num(dog.expectedAdultWeight)}, ${jsonb(dog.weightHistory)}, ${str(dog.microchip)}, ${str(dog.photo)}, ${str(dog.veterinarian)}, ${str(dog.insurance)}, ${str(dog.breeder)}, ${str(dog.healthSummary)},`,
    `  ${textArray(dog.medicalHistory)}, ${textArray(dog.allergies)}, ${jsonb(dog.medicationEntries)},`,
    `  ${num(dog.energy)}, ${num(dog.confidence)}, ${num(dog.fearfulness)}, ${num(dog.resourceGuarding)}, ${num(dog.dogFriendliness)}, ${num(dog.humanFriendliness)}, ${num(dog.noiseSensitivity)},`,
    `  ${textArray(dog.favoriteRewards)}, ${textArray(dog.favoriteToys)}, ${textArray(dog.masteredCommands)}, ${str(dog.exerciseNeed)}, ${str(dog.status)}`,
    ")",
    upsertClause([
      "name", "breed", "birthday", "sex", "color", "weight", "expected_adult_weight", "weight_history",
      "microchip", "photo", "veterinarian", "insurance", "breeder", "health_summary", "medical_history",
      "allergies", "medication_entries", "energy", "confidence", "fearfulness", "resource_guarding",
      "dog_friendliness", "human_friendliness", "noise_sensitivity", "favorite_rewards", "favorite_toys",
      "mastered_commands", "exercise_need", "status",
    ]),
    "",
  );
}

for (const milestone of milestones) {
  lines.push(
    `insert into milestones (id, household_id, title, track, status, dependencies, age_gate_weeks, dog_ids, steps, sources, why) values (`,
    `  ${str(milestone.id)}, ${str(HOUSEHOLD_ID)}, ${str(milestone.title)}, ${str(milestone.track)}, ${str(milestone.status)}, ${textArray(milestone.dependencies)}, ${num(milestone.ageGateWeeks ?? null)},`,
    `  ${uuidArray(milestone.dogIds.map(dogRef))}, ${jsonb(milestone.steps)}, ${jsonb(milestone.sources)}, ${str(milestone.why)}`,
    ")",
    upsertClause(["title", "track", "status", "dependencies", "age_gate_weeks", "dog_ids", "steps", "sources", "why"]),
    "",
  );
}


journalEntries.forEach((entry, index) => {
  lines.push(
    `insert into journal_entries (id, household_id, dog_ids, date, title, text, tags, mood) values (${str(seedId("journal_entries", index))}, ${str(HOUSEHOLD_ID)}, ${uuidArray(entry.dogIds.map(dogRef))}, ${str(entry.date)}, ${str(entry.title)}, ${str(entry.text)}, ${textArray(entry.tags)}, ${str(entry.mood)})`,
    upsertClause(["dog_ids", "date", "title", "text", "tags", "mood"]),
  );
});
lines.push("");

for (const item of exposureItems) {
  lines.push(
    `insert into exposure_items (id, household_id, category, title, dog_ids, status, log) values (${str(item.id)}, ${str(HOUSEHOLD_ID)}, ${str(item.category)}, ${str(item.title)}, ${uuidArray(item.dogIds.map(dogRef))}, ${str(item.status)}, ${jsonb(item.log)})`,
    upsertClause(["category", "title", "dog_ids", "status", "log"]),
  );
}
lines.push("");

relationshipLogs.forEach((log, index) => {
  lines.push(
    `insert into relationship_logs (id, household_id, dog_ids, date, comfort, shared_toys, shared_beds, shared_walks, body_language, resource_guarding, play_quality, corrections, recovery_minutes, notes) values (`,
    `  ${str(seedId("relationship_logs", index))}, ${str(HOUSEHOLD_ID)}, ${uuidArray(log.dogIds.map(dogRef))}, ${str(log.date)}, ${num(log.comfort)}, ${num(log.sharedToys)}, ${num(log.sharedBeds)}, ${num(log.sharedWalks)}, ${num(log.bodyLanguage)}, ${num(log.resourceGuarding)}, ${num(log.playQuality)}, ${num(log.corrections)}, ${num(log.recoveryMinutes)}, ${str(log.notes)}`,
    ")",
    upsertClause([
      "dog_ids", "date", "comfort", "shared_toys", "shared_beds", "shared_walks", "body_language",
      "resource_guarding", "play_quality", "corrections", "recovery_minutes", "notes",
    ]),
  );
});
lines.push("");

// One insert covers what used to be three separate blocks (tasks, health_events,
// calendar_events) — src/data.ts still authors the seed content in the old shapes
// and converts it to Item on the way out, so the SQL only ever sees unified rows.
// Upserts on (household_id, title), matching the unique constraint in schema.sql;
// without it every re-run silently duplicated the whole seed.
items.forEach((item) => {
  lines.push(
    `insert into items (household_id, title, category, intent, kind, recurrence, excluded_dates, date, window_label, start_time, end_time, duration_hours, status, assigned_to, attendees, dog_ids, requires_completion, checklist, checklist_source_milestone_id, requires_log, log_fields, alone_time_required, alone_time_required_amount, coverage_confirmed, coverage_notes, priority, supplies, setting, difficulty, location, formation, related_milestone_id, document_url, rover_visits, prep_steps, rover_instructions, post_steps, notes) values (`,
    `  ${str(HOUSEHOLD_ID)}, ${str(item.title)}, ${str(item.category)}, ${str(item.intent)}, ${str(item.kind)}, ${item.recurrence ? jsonb(item.recurrence) : "NULL"}, ${dateArray(item.excludedDates ?? [])}, ${item.date ? str(item.date) : "NULL"},`,
    `  ${str(item.windowLabel)}, ${item.startTime ? str(item.startTime) : "NULL"}, ${item.endTime ? str(item.endTime) : "NULL"}, ${num(item.durationHours ?? null)}, ${str(item.status)}, ${item.assignedTo ? str(personRef(item.assignedTo)) : "NULL"},`,
    `  ${uuidArray((item.attendees ?? []).map(personRef))}, ${uuidArray((item.dogIds ?? []).map(dogRef))}, ${item.requiresCompletion ? "true" : "false"}, ${jsonb(item.checklist)}, ${item.checklistSourceMilestoneId ? str(item.checklistSourceMilestoneId) : "NULL"}, ${item.requiresLog ? "true" : "false"}, ${jsonb(item.logFields)},`,
    `  ${str(item.aloneTimeRequired)}, ${num(item.aloneTimeRequiredAmount ?? null)}, ${item.coverageConfirmed ? "true" : "false"}, ${str(item.coverageNotes ?? "")}, ${str(item.priority)}, ${textArray(item.supplies)}, ${str(item.setting)}, ${num(item.difficulty)},`,
    `  ${item.location ? str(item.location) : "NULL"}, ${item.formation ? str(item.formation) : "NULL"}, ${item.relatedMilestoneId ? str(item.relatedMilestoneId) : "NULL"}, ${item.documentUrl ? str(item.documentUrl) : "NULL"},`,
    `  ${num(item.roverVisits ?? null)}, ${textArray(item.prepSteps ?? [])}, ${textArray(item.roverInstructions ?? [])}, ${textArray(item.postSteps ?? [])}, ${str(item.notes)}`,
    ")",
    "on conflict (household_id, title) do update set",
    "  category = excluded.category, intent = excluded.intent, kind = excluded.kind, recurrence = excluded.recurrence,",
    "  excluded_dates = excluded.excluded_dates, date = excluded.date, window_label = excluded.window_label,",
    "  start_time = excluded.start_time, end_time = excluded.end_time, duration_hours = excluded.duration_hours,",
    "  status = excluded.status, assigned_to = excluded.assigned_to, attendees = excluded.attendees, dog_ids = excluded.dog_ids,",
    "  requires_completion = excluded.requires_completion, checklist = excluded.checklist,",
    "  checklist_source_milestone_id = excluded.checklist_source_milestone_id,",
    "  requires_log = excluded.requires_log, log_fields = excluded.log_fields,",
    "  alone_time_required = excluded.alone_time_required, alone_time_required_amount = excluded.alone_time_required_amount,",
    "  coverage_confirmed = excluded.coverage_confirmed, coverage_notes = excluded.coverage_notes,",
    "  priority = excluded.priority, supplies = excluded.supplies, setting = excluded.setting, difficulty = excluded.difficulty,",
    "  location = excluded.location, formation = excluded.formation, related_milestone_id = excluded.related_milestone_id,",
    "  document_url = excluded.document_url, rover_visits = excluded.rover_visits, prep_steps = excluded.prep_steps,",
    "  rover_instructions = excluded.rover_instructions, post_steps = excluded.post_steps, notes = excluded.notes;",
    "",
  );
});
lines.push("");

aloneTimeLogs.forEach((log, index) => {
  lines.push(
    `insert into alone_time_logs (id, household_id, date, duration_minutes, dog_ids, notes) values (${str(seedId("alone_time_logs", index))}, ${str(HOUSEHOLD_ID)}, ${str(log.date)}, ${num(log.durationMinutes)}, ${uuidArray(log.dogIds.map(dogRef))}, ${str(log.notes)})`,
    upsertClause(["date", "duration_minutes", "dog_ids", "notes"]),
  );
});

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${lines.length} lines)`);
