import { writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import {
  aloneTimeLogs,
  calendarEvents,
  dogs,
  exposureItems,
  healthEvents,
  journalEntries,
  milestones,
  people,
  relationshipLogs,
  todayTasks,
} from "../src/data";

const HOUSEHOLD_ID = "11111111-1111-1111-1111-111111111111";
const PERSON_IDS: Record<string, string> = {
  andrew: "11111111-1111-1111-1111-111111111112",
  bree: "11111111-1111-1111-1111-111111111113",
};
const DOG_IDS: Record<string, string> = {
  puppy: "11111111-1111-1111-1111-111111111114",
  griz: "11111111-1111-1111-1111-111111111115",
};

function str(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function num(value: number | null | undefined): string {
  return value === null || value === undefined ? "NULL" : String(value);
}

function textArray(values: string[]): string {
  return `ARRAY[${values.map((v) => str(v)).join(", ")}]::text[]`;
}

function uuidArray(values: string[]): string {
  return `ARRAY[${values.map((v) => str(v)).join(", ")}]::uuid[]`;
}

function dateArray(values: string[]): string {
  return `ARRAY[${values.map((v) => str(v)).join(", ")}]::date[]`;
}

function jsonb(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function dogRef(id: string): string {
  const mapped = DOG_IDS[id];
  if (!mapped) throw new Error(`Unknown dog id in seed data: ${id}`);
  return mapped;
}

function personRef(id: string): string {
  const mapped = PERSON_IDS[id];
  if (!mapped) throw new Error(`Unknown person id in seed data: ${id}`);
  return mapped;
}

// people/dogs/milestones/exposure_items keep stable ids across regenerations,
// so re-running this script can safely UPDATE them in place — no risk to
// anything that references them by id (tasks.assigned_to, health_events.dog_id, etc).
function upsertClause(columns: string[]): string {
  return `on conflict (id) do update set ${columns.map((c) => `${c} = excluded.${c}`).join(", ")};`;
}

// health_events/journal_entries/relationship_logs/calendar_events/alone_time_logs
// have no natural key that's safe to upsert on — real user entries (quick-log,
// journal, relationship tracker) can legitimately share a title+date, so a
// content-based unique constraint would block real future inserts. Instead we
// assign each seed row a fixed, deterministic id (stable across regenerations
// as long as array order in src/data.ts doesn't change) and upsert on that id,
// same pattern as milestones/exposure_items but computed rather than hand-authored.
function seedId(table: string, index: number): string {
  const hash = createHash("sha1").update(`dog-life-seed:${table}:${index}`).digest("hex");
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    `5${hash.slice(13, 16)}`,
    `${((parseInt(hash[16], 16) & 0x3) | 0x8).toString(16)}${hash.slice(17, 20)}`,
    hash.slice(20, 32),
  ].join("-");
}

const lines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts from src/data.ts. Do not hand-edit — regenerate instead.",
  "-- Run in the Supabase SQL Editor, after schema.sql, to seed or refresh the app's starting content.",
  "--",
  "-- Safe to re-run: households/people/dogs/milestones/exposure_items are UPSERTED in place by",
  "-- stable id, so re-running just refreshes their fields (breed, sources, dependencies, etc.)",
  "-- without touching anything that references them.",
  "--",
  "-- CAVEAT: milestones/exposure_items upsert also overwrites `status`/`steps`/`log` with the",
  "-- seed defaults (unstarted). If you've already logged real training progress in the app,",
  "-- re-running this will reset that progress back to zero. Safe right now since the puppy",
  "-- isn't picked up yet (nothing real has been logged), but don't blindly re-run this later.",
  "--",
  "-- `tasks` is now UPSERTED too, on (household_id, title) — see the unique constraint added",
  "-- 2026-07-16 in schema.sql. This is what fixed the 'same task duplicated 5+ times on the",
  "-- calendar' bug: every earlier re-run of this file had inserted a fresh duplicate of every",
  "-- task with no conflict handling at all. If you're seeing duplicates from before this fix,",
  "-- run supabase/dedupe-tasks-2026-07-16.sql once, first.",
  "--",
  "-- health_events/journal_entries/relationship_logs/calendar_events/alone_time_logs are now",
  "-- UPSERTED too, on a fixed deterministic id (see seedId() above) rather than a content-based",
  "-- key, since those tables also accept real user-entered rows (quick-log, journal, relationship",
  "-- tracker) that can legitimately repeat a title+date. If you're seeing duplicates from before",
  "-- this fix, run supabase/dedupe-remaining-tables-2026-07-22.sql once, first — it wipes only",
  "-- the seed-originated rows in these 5 tables, safe only because this household hadn't logged",
  "-- any real entries there yet as of 2026-07-22.",
  "--",
  "-- calendar_events changed shape 2026-07-23 (day_of_week/active_from/active_to/time_label/",
  "-- coverage_needed -> recurrence/excluded_dates/start_time/end_time/alone_time_required), and",
  "-- task/calendar-event categories were unified (old \"care\" tasks split into potty/meals). If",
  "-- you're running this against a database from before 2026-07-23, run",
  "-- supabase/migrate-calendar-events-2026-07-23.sql once, first — it backfills the new columns",
  "-- from the old ones and drops the old ones, which this file's UPSERTs now assume are gone.",
  "",
  `insert into households (id, name) values (${str(HOUSEHOLD_ID)}, ${str("Andrew & Bree's household")})`,
  "on conflict (id) do nothing;",
  "",
];

for (const person of people) {
  lines.push(
    `insert into people (id, household_id, name, color) values (${str(personRef(person.id))}, ${str(HOUSEHOLD_ID)}, ${str(person.name)}, ${str(person.color)})`,
    upsertClause(["name", "color"]),
  );
}
lines.push("");

for (const dog of dogs) {
  lines.push(
    `insert into dogs (id, household_id, name, breed, birthday, sex, color, weight, expected_adult_weight, weight_history, microchip, photo, veterinarian, insurance, breeder, health_summary, medical_history, allergies, medication_entries, energy, confidence, fearfulness, resource_guarding, dog_friendliness, human_friendliness, noise_sensitivity, favorite_rewards, favorite_toys, mastered_commands, exercise_need, status) values (`,
    `  ${str(dogRef(dog.id))}, ${str(HOUSEHOLD_ID)}, ${str(dog.name)}, ${str(dog.breed)}, ${dog.birthday ? str(dog.birthday) : "NULL"}, ${str(dog.sex)}, ${str(dog.color)},`,
    `  ${num(dog.weight)}, ${num(dog.expectedAdultWeight)}, ${jsonb(dog.weightHistory)}, ${str(dog.microchip)}, ${str(dog.photo)}, ${str(dog.veterinarian)}, ${str(dog.insurance)}, ${str(dog.breeder)}, ${str(dog.healthSummary)},`,
    `  ${textArray(dog.medicalHistory)}, ${textArray(dog.allergies)}, ${jsonb(dog.medicationEntries)},`,
    `  ${num(dog.energy)}, ${num(dog.confidence)}, ${num(dog.fearfulness)}, ${num(dog.resourceGuarding)}, ${num(dog.dogFriendliness)}, ${num(dog.humanFriendliness)}, ${num(dog.noiseSensitivity)},`,
    `  ${textArray(dog.favoriteRewards)}, ${textArray(dog.favoriteToys)}, ${textArray(dog.masteredCommands)}, ${str(dog.exerciseNeed)}, ${str(dog.status)}`,
    ")",
    upsertClause([
      "name", "breed", "birthday", "sex", "color", "weight", "expected_adult_weight", "weight_history",
      "microchip", "photo", "veterinarian", "insurance", "breeder", "health_summary", "medical_history",
      "allergies", "medication_entries", "energy", "confidence", "fearfulness", "resource_guarding",
      "dog_friendliness", "human_friendliness", "noise_sensitivity", "favorite_rewards", "favorite_toys",
      "mastered_commands", "exercise_need", "status",
    ]),
    "",
  );
}

// Upserts on (household_id, title) — see the unique constraint added in
// schema.sql. Previously this was a plain insert with no conflict handling,
// so every re-run of this file added a fresh duplicate of every task.
for (const task of todayTasks) {
  lines.push(
    `insert into tasks (household_id, title, category, assigned_to, time, duration, priority, supplies, setting, difficulty, dog_ids, checklist, griz_participation, notes, location, formation, related_milestone_id, checklist_schema) values (`,
    `  ${str(HOUSEHOLD_ID)}, ${str(task.title)}, ${str(task.category)}, ${str(personRef(task.assignedTo))}, ${str(task.time)}, ${num(task.duration)}, ${str(task.priority)}, ${textArray(task.supplies)}, ${str(task.setting)}, ${num(task.difficulty)}, ${uuidArray(task.dogIds.map(dogRef))}, ${textArray(task.checklist)}, ${str(task.grizParticipation)}, ${str(task.notes)},`,
    `  ${task.location ? str(task.location) : "NULL"}, ${task.formation ? str(task.formation) : "NULL"}, ${task.relatedMilestoneId ? str(task.relatedMilestoneId) : "NULL"}, ${jsonb(task.checklistSchema ?? [])}`,
    ")",
    "on conflict (household_id, title) do update set",
    "  category = excluded.category, assigned_to = excluded.assigned_to, time = excluded.time, duration = excluded.duration,",
    "  priority = excluded.priority, supplies = excluded.supplies, setting = excluded.setting, difficulty = excluded.difficulty,",
    "  dog_ids = excluded.dog_ids, checklist = excluded.checklist, griz_participation = excluded.griz_participation, notes = excluded.notes,",
    "  location = excluded.location, formation = excluded.formation, related_milestone_id = excluded.related_milestone_id,",
    "  checklist_schema = excluded.checklist_schema;",
    "",
  );
}

for (const milestone of milestones) {
  lines.push(
    `insert into milestones (id, household_id, title, track, status, dependencies, age_gate_weeks, dog_ids, steps, sources, why) values (`,
    `  ${str(milestone.id)}, ${str(HOUSEHOLD_ID)}, ${str(milestone.title)}, ${str(milestone.track)}, ${str(milestone.status)}, ${textArray(milestone.dependencies)}, ${num(milestone.ageGateWeeks ?? null)},`,
    `  ${uuidArray(milestone.dogIds.map(dogRef))}, ${jsonb(milestone.steps)}, ${jsonb(milestone.sources)}, ${str(milestone.why)}`,
    ")",
    upsertClause(["title", "track", "status", "dependencies", "age_gate_weeks", "dog_ids", "steps", "sources", "why"]),
    "",
  );
}

healthEvents.forEach((event, index) => {
  lines.push(
    `insert into health_events (id, household_id, dog_id, title, date, kind, notes, document_url) values (${str(seedId("health_events", index))}, ${str(HOUSEHOLD_ID)}, ${str(dogRef(event.dogId))}, ${str(event.title)}, ${str(event.date)}, ${str(event.kind)}, ${str(event.notes)}, ${event.documentUrl ? str(event.documentUrl) : "NULL"})`,
    upsertClause(["dog_id", "title", "date", "kind", "notes", "document_url"]),
  );
});
lines.push("");

journalEntries.forEach((entry, index) => {
  lines.push(
    `insert into journal_entries (id, household_id, dog_ids, date, title, text, tags, mood) values (${str(seedId("journal_entries", index))}, ${str(HOUSEHOLD_ID)}, ${uuidArray(entry.dogIds.map(dogRef))}, ${str(entry.date)}, ${str(entry.title)}, ${str(entry.text)}, ${textArray(entry.tags)}, ${str(entry.mood)})`,
    upsertClause(["dog_ids", "date", "title", "text", "tags", "mood"]),
  );
});
lines.push("");

for (const item of exposureItems) {
  lines.push(
    `insert into exposure_items (id, household_id, category, title, dog_ids, status, log) values (${str(item.id)}, ${str(HOUSEHOLD_ID)}, ${str(item.category)}, ${str(item.title)}, ${uuidArray(item.dogIds.map(dogRef))}, ${str(item.status)}, ${jsonb(item.log)})`,
    upsertClause(["category", "title", "dog_ids", "status", "log"]),
  );
}
lines.push("");

relationshipLogs.forEach((log, index) => {
  lines.push(
    `insert into relationship_logs (id, household_id, dog_ids, date, comfort, shared_toys, shared_beds, shared_walks, body_language, resource_guarding, play_quality, corrections, recovery_minutes, notes) values (`,
    `  ${str(seedId("relationship_logs", index))}, ${str(HOUSEHOLD_ID)}, ${uuidArray(log.dogIds.map(dogRef))}, ${str(log.date)}, ${num(log.comfort)}, ${num(log.sharedToys)}, ${num(log.sharedBeds)}, ${num(log.sharedWalks)}, ${num(log.bodyLanguage)}, ${num(log.resourceGuarding)}, ${num(log.playQuality)}, ${num(log.corrections)}, ${num(log.recoveryMinutes)}, ${str(log.notes)}`,
    ")",
    upsertClause([
      "dog_ids", "date", "comfort", "shared_toys", "shared_beds", "shared_walks", "body_language",
      "resource_guarding", "play_quality", "corrections", "recovery_minutes", "notes",
    ]),
  );
});
lines.push("");

calendarEvents.forEach((event, index) => {
  lines.push(
    `insert into calendar_events (id, household_id, title, category, kind, recurrence, excluded_dates, date, window_label, start_time, end_time, duration_hours, alone_time_required, alone_time_required_amount, status, importance, notes, attendees, rover_visits, prep_steps, rover_instructions, post_steps) values (`,
    `  ${str(seedId("calendar_events", index))}, ${str(HOUSEHOLD_ID)}, ${str(event.title)}, ${str(event.category)}, ${str(event.kind)}, ${event.recurrence ? jsonb(event.recurrence) : "NULL"}, ${dateArray(event.excludedDates ?? [])}, ${event.date ? str(event.date) : "NULL"},`,
    `  ${str(event.windowLabel)}, ${event.startTime ? str(event.startTime) : "NULL"}, ${event.endTime ? str(event.endTime) : "NULL"}, ${num(event.durationHours ?? null)}, ${str(event.aloneTimeRequired)}, ${num(event.aloneTimeRequiredAmount ?? null)}, ${str(event.status)}, ${event.importance ? str(event.importance) : "NULL"}, ${str(event.notes)},`,
    `  ${uuidArray((event.attendees ?? []).map(personRef))}, ${num(event.roverVisits ?? null)}, ${textArray(event.prepSteps ?? [])}, ${textArray(event.roverInstructions ?? [])}, ${textArray(event.postSteps ?? [])}`,
    ")",
    upsertClause([
      "title", "category", "kind", "recurrence", "excluded_dates", "date", "window_label",
      "start_time", "end_time", "duration_hours", "alone_time_required", "alone_time_required_amount",
      "status", "importance", "notes", "attendees", "rover_visits", "prep_steps", "rover_instructions", "post_steps",
    ]),
  );
});
lines.push("");

aloneTimeLogs.forEach((log, index) => {
  lines.push(
    `insert into alone_time_logs (id, household_id, date, duration_minutes, notes) values (${str(seedId("alone_time_logs", index))}, ${str(HOUSEHOLD_ID)}, ${str(log.date)}, ${num(log.durationMinutes)}, ${str(log.notes)})`,
    upsertClause(["date", "duration_minutes", "notes"]),
  );
});

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${lines.length} lines)`);
