import {
  AloneTimeLog,
  CalendarEvent,
  Dog,
  ExposureItem,
  FeedbackLoopRule,
  GroceryListItem,
  HealthEvent,
  Household,
  InventoryCategory,
  InventoryItem,
  JournalEntry,
  Location,
  Meal,
  Milestone,
  Person,
  RecipeIngredient,
  RelationshipLog,
  Task,
} from "./types";

export const households: Household[] = [
  {
    id: "andrew-bree",
    name: "Andrew & Bree's household",
    memberIds: ["andrew", "bree"],
    dogIds: ["puppy", "griz"],
  },
];

export const people: Person[] = [
  {
    id: "andrew",
    householdId: "andrew-bree",
    name: "Andrew",
    color: "#2f6f64",
  },
  {
    id: "bree",
    householdId: "andrew-bree",
    name: "Bree",
    color: "#b46b55",
  },
];

export const dogs: Dog[] = [
  {
    id: "puppy",
    householdId: "andrew-bree",
    name: "New Puppy",
    breed: "Goldendoodle",
    birthday: "",
    sex: "Unknown (confirmed at pickup)",
    color: "#d6a657",
    weight: 0,
    expectedAdultWeight: 35,
    weightHistory: [],
    microchip: "Pending — breeder-provided at pickup",
    photo:
      "https://images.unsplash.com/photo-1593134257782-e89567b7718a?auto=format&fit=crop&w=700&q=80",
    veterinarian: "Canyons Vet",
    insurance: "To compare",
    breeder: "Ruby Doodles Louisiana",
    healthSummary:
      "Not yet picked up. Pickup scheduled Saturday, August 1, 2026 (mid-afternoon) from Ruby Doodles Louisiana. First vet appointment August 3, 2026 at 2:00 PM with Canyons Vet. Estimated adult weight 30-40 lbs (max). Name, sex, birthday, and microchip confirmed at pickup — see docs/knowledge/puppy-life-knowledge.md.",
    medicalHistory: [
      "Breeder health records pending — to be uploaded after pickup",
      "First vet appointment: August 3, 2026 at 2:00 PM (Canyons Vet)",
    ],
    allergies: [],
    medicationEntries: [],
    energy: 50,
    confidence: 50,
    fearfulness: 50,
    resourceGuarding: 50,
    dogFriendliness: 50,
    humanFriendliness: 50,
    noiseSensitivity: 50,
    favoriteRewards: ["Soft treats", "Kibble tosses", "Praise"],
    favoriteToys: ["Snuffle mat", "Rope", "Crinkle toy"],
    masteredCommands: [],
    exerciseNeed: "Short age-appropriate sessions with naps protected",
    status: "puppy",
  },
  {
    id: "griz",
    householdId: "andrew-bree",
    name: "Griz",
    breed: "Adult dog",
    birthday: "2020-08-20",
    sex: "Male",
    color: "#6d7d8b",
    weight: 64,
    expectedAdultWeight: 64,
    weightHistory: [
      { date: "2026-05-01", pounds: 65, notes: "Spring baseline" },
      { date: "2026-07-09", pounds: 64, notes: "Stable adult weight" },
    ],
    microchip: "On file",
    photo:
      "https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=700&q=80",
    veterinarian: "Canyons Vet",
    insurance: "On file",
    breeder: "On file",
    healthSummary:
      "Adult maintenance, updated per household 2026-07-15 (supersedes the 5/8/2024 care sheet's medication specifics): pain management is now Tramadol + extra-strength Tylenol + Gabapentin 2x/day (after breakfast and before bed) rather than Carprofen; joint/mobility support comes from a therapeutic Hill's Science Diet Healthy Mobility diet plus Dasuquin and MYOS Muscle Formula. Paws prone to injury — proactive mud-buster/towel care after outdoor time. Decompression exercise, grooming, and relationship support during puppy integration. Schedule note: Griz is flexible on exact meal/potty timing, so his routine is merged onto the puppy's cadence (7:45 AM breakfast, 6:00 PM dinner, morning walk potty) rather than run separately — see the household daily schedule in docs/knowledge/puppy-life-knowledge.md.",
    medicalHistory: [
      "Adult wellness records on file",
      "No active restrictions logged",
      "Paws prone to injury — proactive care needed after muddy walks",
    ],
    allergies: [],
    medicationEntries: [
      { id: "griz-med-meal-mixers", name: "Purina Meal Mixers (Chicken)", kind: "supplement", dosage: "Per label", frequency: "Daily, with breakfast", notes: "Food topper" },
      { id: "griz-med-dasuquin", name: "Nutramax Dasuquin", kind: "supplement", dosage: "Small/medium dog dose", frequency: "Daily, with breakfast", notes: "Joint support" },
      { id: "griz-med-kibble", name: "Hill's Science Diet Adult Healthy Mobility Small Bites (Chicken, Brown Rice & Barley)", kind: "supplement", dosage: "1.5 cups", frequency: "2x/day, breakfast & dinner", notes: "Therapeutic joint-mobility diet; kibble soaked in water" },
      { id: "griz-med-yogurt", name: "Greek yogurt or cottage cheese", kind: "supplement", dosage: "1 tablespoon", frequency: "2x/day, breakfast & before bed", notes: "" },
      { id: "griz-med-myos", name: "MYOS Muscle Formula", kind: "supplement", dosage: "1 tablespoon", frequency: "2x/day, breakfast & dinner", notes: "" },
      { id: "griz-med-tramadol", name: "Tramadol", kind: "medication", dosage: "100mg (1 tablet)", frequency: "2x/day, after breakfast & before bed", notes: "Pain management" },
      { id: "griz-med-tylenol", name: "Extra Strength Tylenol", kind: "medication", dosage: "1/2 tablet", frequency: "2x/day, after breakfast & before bed", notes: "Pain management — vet-directed human OTC dose" },
      { id: "griz-med-gabapentin", name: "Gabapentin", kind: "medication", dosage: "100mg (1 tablet)", frequency: "2x/day, after breakfast & before bed", notes: "Pain management" },
      { id: "griz-med-cheese", name: "American cheese", kind: "supplement", dosage: "1/10 slice", frequency: "Daily, after breakfast", notes: "Used to help take pills" },
      { id: "griz-med-dental-stick", name: "Dingo dental stick", kind: "supplement", dosage: "1 stick", frequency: "Daily, after breakfast", notes: "Dental chew" },
      { id: "griz-med-fortiflora", name: "Purina Pro Plan Veterinary Supplements FortiFlora Probiotic Powder", kind: "supplement", dosage: "1 packet", frequency: "Daily, with dinner", notes: "" },
      { id: "griz-med-pumpkin", name: "Canned 100% pumpkin", kind: "supplement", dosage: "1 tablespoon", frequency: "Daily, with dinner", notes: "" },
      { id: "griz-med-preventive", name: "Flea/tick + heartworm prevention", kind: "preventive", dosage: "1 dose", frequency: "Monthly", notes: "Carried over from prior regimen — please confirm this is still active" },
    ],
    energy: 66,
    confidence: 78,
    fearfulness: 18,
    resourceGuarding: 18,
    dogFriendliness: 72,
    humanFriendliness: 84,
    noiseSensitivity: 24,
    favoriteRewards: ["Cheese", "Tug", "Release to sniff", "Beef lung tips", "Bill Jack soft bits"],
    favoriteToys: ["Ball", "Tug toy", "Puzzle feeder", "Frisbee"],
    masteredCommands: [
      "Sit",
      "Down",
      "Stay",
      "Recall",
      "Place",
      "Look at Me",
      "Up",
      "Roll Over",
      "Speak",
      "Play Dead",
      "Paw",
      "Fetch",
      "Settle",
      "Spin",
      "Give",
      "Leave It",
      "Heel",
      "Wait",
      "Leash/Easy",
      "Get Back",
      "Gentle",
      "Free",
    ],
    exerciseNeed: "Daily decompression walk and enrichment",
    status: "adult",
  },
];

// Reference locations for tasks/events — not a Supabase-synced collection, just a
// shared lookup so activities can point at a consistent place. School-yard dates
// below are the real 2026-27 Salt Lake City School District calendar; only the
// exact bell time (~7:45 AM-3:00 PM) is still an estimate.
export const locations: Location[] = [
  {
    id: "home-fenced-yard",
    name: "Home — fenced yard",
    type: "fenced-yard",
    availability: "Always available",
    notes: "Primary off-leash potty and play space. Safe for solo puppy use once reliably contained.",
  },
  {
    id: "home-indoor",
    name: "Home — indoor",
    type: "indoor",
    availability: "Always available",
    notes: "Meals, crate time, handling/grooming reps, and settle practice. Hardwood-floor room is the go-to for crating during outings (easiest cleanup).",
  },
  {
    id: "parkview-elementary-yard",
    name: "Parkview Elementary yard",
    type: "school-yard",
    availability:
      "Real 2026-27 Salt Lake City School District calendar. Unavailable on school days (~7:45 AM-3:00 PM, exact bell time still TBD) — school days run Aug 18 - Oct 23, 2026 (Q1); Oct 26, 2026 - Jan 8, 2027 (Q2, excluding Nov 25 non-student day and Nov 26-27 Thanksgiving Break and Dec 21, 2026 - Jan 1, 2027 Winter Break); Jan 11 - Mar 19, 2027 (Q3, excluding Jan 18 MLK Day, Feb 15 Presidents Day, and Feb 26 non-student day); Mar 22 - May 27, 2027 (Q4, excluding Mar 29 - Apr 2 Spring Break). Available evenings, weekends, all listed breaks/holidays, and summer (school out May 26-28, 2027 through summer). Currently summer break, so open now.",
    notes: "Large open grass, good for recall and off-leash practice once school is back in session and timing is respected.",
  },
  {
    id: "public-park",
    name: "Public park",
    type: "park",
    availability: "Always available; busier on weekends/evenings",
    notes: "Good for socialization exposure — other dogs, kids, novel surfaces.",
  },
  {
    id: "walking-paths",
    name: "Neighborhood walking paths",
    type: "trail",
    availability: "Always available",
    notes: "Default route for parallel decompression walks and leash training.",
  },
  {
    id: "hiking-trail",
    name: "Local hiking trail",
    type: "trail",
    availability: "Always available; weather/season dependent",
    notes: "Griz-only until the puppy is old enough and vaccinated for trail exposure — good solo-dog-time option while the puppy is elsewhere (e.g. at the vet).",
  },
  {
    id: "canyons-vet",
    name: "Canyons Vet",
    type: "vet",
    availability: "By appointment",
    notes: "Shared vet for both dogs.",
  },
];

export const todayTasks: Task[] = [
  {
    id: "morning-potty",
    title: "Morning potty",
    category: "potty",
    assignedTo: "andrew",
    time: "7:15 AM",
    duration: 5,
    priority: "essential",
    supplies: ["Treat pouch", "Leash"],
    setting: "outdoor",
    difficulty: 1,
    dogIds: ["puppy", "griz"],
    checklist: ["Outside", "Reward", "Pee", "Poop", "No accidents"],
    checklistSchema: [
      { itemName: "Peed", dataType: "counter" },
      { itemName: "Pooped", dataType: "counter" },
      { itemName: "Playtime occurred", dataType: "boolean" },
      { itemName: "Playtime duration (min)", dataType: "duration_minutes" },
      { itemName: "Treats given", dataType: "counter" },
      { itemName: "Notes", dataType: "free_text" },
    ],
    grizParticipation: "yes",
    location: "home-fenced-yard",
    formation: "together",
    notes:
      "Keep it boring, reward fast, log how quickly the puppy goes. Real cadence once home: potty every ~2 hours (rule of thumb — hourly frequency roughly equals age in months), always right after eating or waking. Griz's morning-walk poop happens naturally in this same window, so this is one joint trip out rather than two separate ones — his schedule is flexible enough to slide onto the puppy's timing (see the merged-schedule note in the knowledge doc). No playtime or extra praise during the potty trip itself — calm acknowledgment only when the behavior happens, then a short play reward after.",
  },
  {
    id: "breakfast-reset",
    title: "Breakfast + settle reset",
    category: "meals",
    assignedTo: "bree",
    time: "7:45 AM",
    duration: 15,
    priority: "essential",
    supplies: ["Food", "Water", "Crate", "Puzzle feeder"],
    setting: "indoor",
    difficulty: 2,
    dogIds: ["puppy", "griz"],
    checklist: ["Separate meals", "Water refreshed", "Calm release", "Two-minute settle"],
    grizParticipation: "separate",
    location: "home-indoor",
    formation: "separate-rooms",
    notes:
      "Feed separately until relationship score stays above 80 for two weeks. Real cadence once home: puppy ~0.25 cup per serving, 4x/day total; water refreshed every ~2 hours (~1 oz per lb body weight/day total). Griz's usual ~1 cup morning meal (+ Gabapentin, Carprofen, salmon oil, Dasuquin chew) is folded into this same slot instead of running on his own separate morning schedule.",
  },
  {
    id: "evening-meal",
    title: "Evening meal (both dogs)",
    category: "meals",
    assignedTo: "andrew",
    time: "6:00 PM",
    duration: 10,
    priority: "essential",
    supplies: ["Food", "Water", "Crate", "Griz's meds"],
    setting: "indoor",
    difficulty: 1,
    dogIds: ["puppy", "griz"],
    checklist: ["Separate meals", "Griz's evening meds + FortiFlora given", "Water refreshed", "Calm release"],
    grizParticipation: "separate",
    location: "home-indoor",
    formation: "separate-rooms",
    notes:
      "Griz's second daily meal (+ Gabapentin, Carprofen, FortiFlora probiotic) is scheduled here instead of on his own timetable, right before the 6:15 PM parallel walk — he's a flexible, chill adult who adapts easily to the puppy's cadence. This is one of the puppy's 4 daily feeds; the other two (midday) are puppy-only and don't need to move Griz's routine at all.",
  },
  {
    id: "name-recall",
    title: "Name + recall foundation",
    category: "training",
    assignedTo: "andrew",
    time: "12:15 PM",
    duration: 6,
    priority: "important",
    supplies: ["Soft treats", "Clicker or marker word"],
    setting: "indoor",
    difficulty: 2,
    dogIds: ["puppy"],
    checklist: ["Say name once", "Mark eye contact", "Treat at leg", "Five happy recalls"],
    grizParticipation: "managed",
    location: "home-indoor",
    formation: "solo",
    relatedMilestoneId: "name-recognition",
    notes: "End before attention fades. Griz can practice place for parallel rewards. Week 1 focus per the real training schedule: Name/Look at Me, Leash, Leave It, and Sit are taught in parallel starting pickup week.",
  },
  {
    id: "parallel-walk",
    title: "Parallel decompression walk",
    category: "relationship",
    assignedTo: "bree",
    time: "6:15 PM",
    duration: 18,
    priority: "important",
    supplies: ["Two leashes", "Treats", "Water"],
    setting: "outdoor",
    difficulty: 3,
    dogIds: ["puppy", "griz"],
    checklist: ["Start with distance", "Reward check-ins", "No shared toy", "Log body language"],
    grizParticipation: "yes",
    location: "walking-paths",
    formation: "parallel-buffered",
    notes: "Keep dogs parallel, not face-to-face — ideally a human walking each dog with a person-width gap between them (dog, human, human, dog), not dog-to-dog. Increase distance if either dog stiffens.",
  },
  {
    id: "handling",
    title: "Cooperative handling minis",
    category: "handling",
    assignedTo: "bree",
    time: "8:30 PM",
    duration: 7,
    priority: "optional",
    supplies: ["Brush", "Treats", "Toothbrush"],
    setting: "indoor",
    difficulty: 2,
    dogIds: ["puppy"],
    checklist: ["Touch paws", "Lift lips", "Brush one stroke", "End with play"],
    grizParticipation: "managed",
    location: "home-indoor",
    formation: "solo",
    relatedMilestoneId: "grooming-desensitizing",
    notes: "Consent-based pace. If the puppy withdraws twice, stop and make tomorrow easier. Real cadence once home: brush hair daily (evenings), dental treats 2x/week (Mon, Thu), ear cleaning + teeth brushing weekly (Sunday), bath bi-weekly.",
  },
];

export const milestones: Milestone[] = [
  {
    id: "marker-word",
    title: "Marker word",
    track: "obedience",
    dogIds: ["puppy"],
    status: "current",
    dependencies: [],
    steps: [
      { title: "Charge marker", successCriteria: "10 marker-treat reps with eager orientation", sessionsRequired: 2, completedSessions: 0 },
      { title: "Use on eye contact", successCriteria: "Marks correct behavior within one second", sessionsRequired: 3, completedSessions: 0 },
    ],
    sources: [
      { title: "Clicker training basics", type: "article", url: "https://www.akc.org/expert-advice/training/clicker-training-your-dog-mark-and-reward/", publisher: "AKC" },
      { title: "Marker training explanation", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+marker+training+puppy", publisher: "Kikopup" },
      { title: "Positive reinforcement training", type: "article", url: "https://www.humanesociety.org/resources/positive-reinforcement-training", publisher: "Humane Society" },
    ],
    why: "A consistent marker lets every later skill become easier to teach and measure.",
  },
  {
    id: "sit",
    title: "Sit",
    track: "obedience",
    dogIds: ["puppy"],
    status: "locked",
    dependencies: ["marker-word", "name-recognition"],
    ageGateWeeks: 1,
    steps: [
      { title: "Lure into sit", successCriteria: "Follows lure and sits 8 of 10 reps (beginner)", sessionsRequired: 2, completedSessions: 0 },
      { title: "Fade food lure", successCriteria: "Lure with one hand, feed from the other, then responds to empty-hand cue 8 of 10 reps (medium)", sessionsRequired: 3, completedSessions: 0 },
      { title: "Verbal cue only", successCriteria: "Sits on verbal cue alone with no hand signal, before bowl/door/leash clip (hard)", sessionsRequired: 4, completedSessions: 0 },
    ],
    sources: [
      { title: "Sit — Howcast", type: "video", url: "https://www.howcast.com/videos/499142-how-to-teach-your-dog-to-sit-dog-training", publisher: "Dog Rules reference" },
      { title: "Teach your puppy to sit", type: "article", url: "https://www.akc.org/expert-advice/training/how-to-teach-your-dog-to-sit/", publisher: "AKC" },
      { title: "Lure-and-reward training plan", type: "plan", url: "https://www.akc.org/expert-advice/training/lure-reward-training/", publisher: "AKC" },
    ],
    why: "Week 1 command per the real training schedule — taught alongside Name, Leash, and Leave It starting the week of pickup (8/1/26). Locked until marker word and name recognition have real logged sessions.",
  },
  {
    id: "down",
    title: "Lay",
    track: "obedience",
    dogIds: ["puppy"],
    status: "locked",
    dependencies: ["sit", "food-lure", "focus"],
    ageGateWeeks: 2,
    steps: [
      { title: "Lure elbows down from sit", successCriteria: "Starts from the sit position and both elbows touch floor without pawing", sessionsRequired: 3, completedSessions: 0 },
      { title: "Hold down", successCriteria: "Maintains down for 10 seconds across 3 sessions", sessionsRequired: 3, completedSessions: 0 },
      { title: "Relaxed down", successCriteria: "Can down on mat after light play", sessionsRequired: 4, completedSessions: 0 },
    ],
    sources: [
      { title: "Lay — reference video 1", type: "video", url: "https://www.youtube.com/watch?v=hHKtUp9-xbc", publisher: "Dog Rules reference" },
      { title: "Lay — reference video 2", type: "video", url: "https://www.youtube.com/watch?v=ENcl04S6tio&t=26s", publisher: "Dog Rules reference" },
      { title: "Teach down", type: "article", url: "https://www.akc.org/expert-advice/training/how-to-teach-your-dog-to-lie-down/", publisher: "AKC" },
    ],
    why: "Week 2 command per the real training schedule (starts from the Sit position). Needs sit, a reliable lure follow, and three short focus sessions before it becomes a primary task.",
  },
  {
    id: "leave-it",
    title: "Leave it",
    track: "obedience",
    dogIds: ["puppy", "griz"],
    status: "locked",
    dependencies: ["marker-word", "impulse-control", "drop-it"],
    ageGateWeeks: 1,
    steps: [
      { title: "Closed fist game", successCriteria: "Looks away from covered treat 8 of 10 reps (beginner)", sessionsRequired: 3, completedSessions: 0 },
      { title: "Food on ground, hand covering", successCriteria: "Leaves visible item when cued (medium) — major rule: never reward speed over patience, never let the dog win by stealing", sessionsRequired: 4, completedSessions: 0 },
      { title: "Real-world proofing", successCriteria: "Passes low-value sidewalk items, leaves, or trash on a walk (hard)", sessionsRequired: 5, completedSessions: 0 },
    ],
    sources: [
      { title: "It's Your Choice — impulse training", type: "video", url: "https://www.youtube.com/watch?v=QIuxm5r17nE", publisher: "Dog Rules reference" },
      { title: "Leave It advanced (Zak George)", type: "video", url: "https://www.youtube.com/watch?v=dGncNgiHEjM", publisher: "Zak George" },
      { title: "Teach leave it", type: "article", url: "https://www.akc.org/expert-advice/training/learning-the-leave-it-command/", publisher: "AKC" },
    ],
    why: "Week 1 command per the real training schedule. Still locked because drop it has not started and impulse control is below the readiness threshold.",
  },
  {
    id: "loose-leash",
    title: "Loose leash walking",
    track: "obedience",
    dogIds: ["puppy", "griz"],
    status: "locked",
    dependencies: ["sit", "recall-foundation", "outside-confidence"],
    ageGateWeeks: 1,
    steps: [
      { title: "Circles indoors", successCriteria: "Stays near handler / makes eye contact walking circles indoors (beginner)", sessionsRequired: 3, completedSessions: 0 },
      { title: "Change location and distance", successCriteria: "Maintains slack leash with more distractions present (medium)", sessionsRequired: 4, completedSessions: 0 },
      { title: "Add other skills while leashed", successCriteria: "Holds other cues together in new environments; stop-and-redirect if pulling, never yell (hard)", sessionsRequired: 5, completedSessions: 0 },
    ],
    sources: [
      { title: "Leash — 8 min mark", type: "video", url: "https://www.youtube.com/watch?v=FG9xSgN86BM", publisher: "Dog Rules reference" },
      { title: "Intermediate walking training", type: "video", url: "https://www.youtube.com/watch?v=3gHPXpsPzxo", publisher: "Dog Rules reference" },
      { title: "Mistakes of leash walking", type: "video", url: "https://www.youtube.com/watch?v=hX1DMZIMLPk", publisher: "Dog Rules reference" },
    ],
    why: "Week 1 command per the real training schedule. Starts after recall foundation, outside confidence, and vaccine guidance line up — the app schedules parallel decompression walks with Griz in the meantime.",
  },
  {
    id: "dog-park",
    title: "Dog park readiness",
    track: "socialization",
    dogIds: ["puppy"],
    status: "locked",
    dependencies: ["vaccines-complete", "recall-foundation", "loose-leash", "dog-body-language"],
    ageGateWeeks: 24,
    steps: [
      { title: "Observe dogs at distance", successCriteria: "Relaxed body for 10 minutes at 50+ feet", sessionsRequired: 4, completedSessions: 0 },
      { title: "One known dog parallel walk", successCriteria: "Loose body and recovery after greetings", sessionsRequired: 4, completedSessions: 0 },
      { title: "Recall around dogs", successCriteria: "Responds 8 of 10 times around one calm dog", sessionsRequired: 6, completedSessions: 0 },
    ],
    sources: [
      { title: "Dog park safety", type: "article", url: "https://www.akc.org/expert-advice/lifestyle/dog-park-etiquette-tips/", publisher: "AKC" },
      { title: "Puppy socialization position statement", type: "plan", url: "https://avsab.org/resources/position-statements/", publisher: "AVSAB" },
      { title: "Reading dog body language", type: "video", url: "https://www.youtube.com/results?search_query=dog+body+language+play+signals+training", publisher: "YouTube behavior library" },
    ],
    why: "Dog park access requires vaccines, recall, loose leash skills, and consistently calm dog-to-dog body language.",
  },
  ...([
    {
      id: "name-recognition",
      title: "Name / Look at Me",
      track: "obedience",
      dependencies: [],
      ageGateWeeks: 1,
      steps: [
        { title: "Lure eye contact", successCriteria: "Turns head toward handler on name/lure 8 of 10 reps in a quiet room (beginner)", sessionsRequired: 2, completedSessions: 0 },
        { title: "Distance and unexpected timing", successCriteria: "Orients from across the room, mid-walk, or mid-play (medium)", sessionsRequired: 3, completedSessions: 0 },
        { title: "Different people, places, distractions", successCriteria: "Responds to name for different people in different places 8 of 10 reps (hard)", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "Look at Me — reference video", type: "video", url: "https://www.youtube.com/watch?v=FG9xSgN86BM", publisher: "Dog Rules reference" },
        { title: "Give me your attention you booger", type: "article", url: "https://kaufmannspuppytraining.com/en/get-dogs-attention/", publisher: "Kaufmann's Puppy Training" },
        { title: "How to Teach Your Dog Their Name", type: "article", url: "https://www.akc.org/expert-advice/training/how-to-teach-dog-name/", publisher: "AKC" },
      ],
      why: "Week 1 command per the real training schedule. Reliable orientation to the puppy's name is the first building block every later cue depends on, since a dog can't respond to instruction it isn't already listening for.",
    },
    {
      id: "food-lure",
      title: "Food lure mechanics",
      track: "obedience",
      dependencies: [],
      steps: [
        { title: "Nose-follows-hand", successCriteria: "Tracks a treat in a closed fist through a simple path 8 of 10 reps", sessionsRequired: 2, completedSessions: 0 },
        { title: "Lure into basic position shifts", successCriteria: "Follows lure into a sit or a turn without freezing or jumping", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "Lure-and-reward training plan", type: "plan", url: "https://www.akc.org/expert-advice/training/lure-reward-training/", publisher: "AKC" },
        { title: "Lure training fundamentals", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+lure+training+fundamentals+puppy", publisher: "Kikopup" },
        { title: "Positive reinforcement training basics", type: "article", url: "https://www.humanesociety.org/resources/positive-reinforcement-training", publisher: "Humane Society" },
      ],
      why: "Clean lure mechanics (steady hand, correct pace, timely release) are the mechanical skill behind sit, down, touch, shake, spin, and roll over, so it is worth teaching as its own milestone before those cues stack on top of it.",
    },
    {
      id: "focus",
      title: "Focus / engagement",
      track: "obedience",
      dependencies: ["name-recognition"],
      steps: [
        { title: "Eye contact for a treat", successCriteria: "Offers voluntary eye contact 8 of 10 reps indoors", sessionsRequired: 2, completedSessions: 0 },
        { title: "Hold eye contact briefly", successCriteria: "Holds eye contact 3 seconds before reward", sessionsRequired: 3, completedSessions: 0 },
        { title: "Focus around mild distraction", successCriteria: "Re-engages with handler within 2 seconds of a mild distraction outdoors", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "Grab & Hold Your Dog's Attention With the \"Watch Me\" Command", type: "article", url: "https://www.akc.org/expert-advice/training/watch-me-command-grab-dogs-attention/", publisher: "AKC" },
        { title: "How to Train Your Dog to Stay Focused Around Distractions", type: "article", url: "https://www.akc.org/expert-advice/training/training-dogs-to-ignore-distractions/", publisher: "AKC" },
        { title: "Engagement and focus training", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+engagement+focus+training+puppy", publisher: "Kikopup" },
      ],
      why: "Builds on name recognition by teaching sustained voluntary attention, which down, stay, spin, heel, and impulse control all rely on to hold the dog's attention through a full behavior.",
    },
    {
      id: "impulse-control",
      title: "Impulse control",
      track: "obedience",
      dependencies: ["focus"],
      steps: [
        { title: "It's Yer Choice / bowl game", successCriteria: "Waits without lunging while food bowl lowers 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
        { title: "Wait at doorway / crate", successCriteria: "Holds position while door opens until released", sessionsRequired: 3, completedSessions: 0 },
        { title: "Settle during play arousal", successCriteria: "Interrupts play and offers a sit within 3 seconds of cue", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "It's Your Choice — impulse training", type: "video", url: "https://www.youtube.com/watch?v=QIuxm5r17nE", publisher: "Dog Rules reference" },
        { title: "13 Training Games", type: "article", url: "https://journeydogtraining.com/13-dog-training-games/", publisher: "Journey Dog Training" },
        { title: "Impulse Control for Dogs: Dog Self-Control Training", type: "article", url: "https://www.akc.org/expert-advice/training/teaching-your-dog-self-control/", publisher: "AKC" },
      ],
      why: "Also listed as its own item in the 8-16 week training schedule. Extends focus into self-restraint around real motivators (food, doors, arousal), and is the readiness gate leave-it and wait depend on before they can be proofed in daily life.",
    },
    {
      id: "drop-it",
      title: "Drop it",
      track: "obedience",
      dependencies: ["marker-word", "food-lure"],
      steps: [
        { title: "Trade for low-value toy", successCriteria: "Releases a low-value toy for a treat trade 8 of 10 reps", sessionsRequired: 2, completedSessions: 0 },
        { title: "Add verbal cue", successCriteria: "Drops item on verbal cue before treat is shown 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
        { title: "Proof with higher-value items", successCriteria: "Drops a favorite toy or found object on first cue without chase", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach Your Dog to Drop It", type: "article", url: "https://www.akc.org/expert-advice/training/teaching-your-dog-to-drop-it/", publisher: "AKC" },
        { title: "Drop it without a chase", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+drop+it+trade+training", publisher: "Kikopup" },
        { title: "Positive reinforcement training basics", type: "article", url: "https://www.humanesociety.org/resources/positive-reinforcement-training", publisher: "Humane Society" },
      ],
      why: "Teaches a fair trade instead of a grab, which prevents resource guarding and is required before leave-it (impulse control around items already in the mouth) and retrieve (releasing the toy into the handler's hand).",
    },
    {
      id: "recall-foundation",
      title: "Come",
      track: "obedience",
      dependencies: ["name-recognition", "marker-word"],
      ageGateWeeks: 4,
      steps: [
        { title: "Hand at dog's face", successCriteria: "Comes to hand held right in front of face 8 of 10 reps (beginner) — 1 kibble for alerting attention, 1 treat for a nose-bump", sessionsRequired: 2, completedSessions: 0 },
        { title: "Hand off to the side", successCriteria: "Comes with hand held off to the side of the dog's face (medium)", sessionsRequired: 3, completedSessions: 0 },
        { title: "Standing a few feet away, verbal only", successCriteria: "Recalls from a few feet away on verbal cue alone (hard/expert)", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "Target training — intro to hand signals", type: "video", url: "https://www.youtube.com/watch?v=QIuxm5r17nE", publisher: "Dog Rules reference" },
        { title: "Back and forth exercise", type: "video", url: "https://www.youtube.com/watch?v=rwldfBjFsdE", publisher: "Dog Rules reference" },
        { title: "Reliable Recall: Teaching Your Dog to Always Come When Called", type: "article", url: "https://www.akc.org/expert-advice/training/reliable-recall-train-dogs-to-come-when-called/", publisher: "AKC" },
      ],
      why: "Week 4 command per the real training schedule. Establishes the basic come-when-called response in low-distraction settings, which loose leash walking, dog park readiness, and later advanced/emergency recall all build distance and distraction on top of.",
    },
    {
      id: "outside-confidence",
      title: "Outside confidence",
      track: "confidence",
      dependencies: ["name-recognition"],
      steps: [
        { title: "Front yard exposure", successCriteria: "Explores front yard with loose body language for 5 minutes", sessionsRequired: 3, completedSessions: 0 },
        { title: "Novel surfaces and sounds", successCriteria: "Recovers within 5 seconds after a mild startle outdoors", sessionsRequired: 4, completedSessions: 0 },
        { title: "Quiet street exposure", successCriteria: "Walks past a passing car or jogger without freezing or bolting", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "Confident Puppy: How Do You Raise a Secure Young Dog", type: "article", url: "https://www.akc.org/expert-advice/training/how-do-you-raise-a-confident-puppy/", publisher: "AKC" },
        { title: "Puppy Socialization: Why, When, and How to Do It Right", type: "plan", url: "https://www.akc.org/expert-advice/training/puppy-socialization/", publisher: "AKC" },
        { title: "Building outdoor confidence in puppies", type: "video", url: "https://www.youtube.com/results?search_query=puppy+outdoor+confidence+building+socialization", publisher: "YouTube behavior library" },
      ],
      why: "Builds calm, curious body language in outdoor environments before leash pressure and traffic are added, which loose leash walking depends on to avoid pairing the leash itself with stress.",
    },
    {
      id: "vaccines-complete",
      title: "Puppy vaccine series complete",
      track: "health",
      dependencies: [],
      ageGateWeeks: 16,
      steps: [
        { title: "Puppy series 1 of 3", successCriteria: "First distemper/parvo combo vaccine given at 6-8 weeks, no adverse reaction", sessionsRequired: 1, completedSessions: 0 },
        { title: "Puppy series 2 of 3", successCriteria: "Second combo booster given 3-4 weeks after the first, no adverse reaction", sessionsRequired: 1, completedSessions: 0 },
        { title: "Puppy series 3 of 3 + vet clearance", successCriteria: "Final booster given at 16+ weeks and vet confirms full protection for public spaces", sessionsRequired: 1, completedSessions: 0 },
      ],
      sources: [
        { title: "Puppy Vaccination Schedule: What Shots Do Puppies Need?", type: "article", url: "https://www.akc.org/expert-advice/health/puppy-shots-complete-guide/", publisher: "AKC" },
        { title: "2022 AAHA Canine Vaccination Guidelines", type: "plan", url: "https://www.aaha.org/resources/2022-aaha-canine-vaccination-guidelines/", publisher: "AAHA" },
        { title: "Puppy Vaccine Schedule", type: "article", url: "https://vcahospitals.com/pediatric/puppy/health-wellness/puppy-vaccine-schedule", publisher: "VCA Animal Hospitals" },
      ],
      why: "This is a medical gate rather than a training skill: dog park readiness and any off-property socialization around unknown dogs should not unlock until the vet confirms the full puppy series is complete.",
    },
    {
      id: "dog-body-language",
      title: "Reading dog body language",
      track: "socialization",
      dependencies: [],
      steps: [
        { title: "Identify calm vs. stiff body signals", successCriteria: "Handler correctly labels loose vs. tense body language in 8 of 10 photos or clips", sessionsRequired: 2, completedSessions: 0 },
        { title: "Live observation at distance", successCriteria: "Handler flags a stress signal in a real dog interaction within 3 seconds", sessionsRequired: 3, completedSessions: 0 },
        { title: "Apply during a supervised greeting", successCriteria: "Handler interrupts a greeting before escalation using body-language cues", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "Dog Body Language", type: "article", url: "https://www.akc.org/expert-advice/training/dog-body-language/", publisher: "AKC" },
        { title: "7 Tips: Canine Body Language", type: "article", url: "https://www.aspcapro.org/resource/7-tips-canine-body-language", publisher: "ASPCA" },
        { title: "Reading dog body language and play signals", type: "video", url: "https://www.youtube.com/results?search_query=dog+body+language+play+signals+training", publisher: "YouTube behavior library" },
      ],
      why: "This is a handler skill, not a dog skill: recognizing stress and play signals is what makes dog park readiness and any dog-to-dog introduction safe to attempt, since escalation must be caught before it happens.",
    },
    {
      id: "stay",
      title: "Stay",
      track: "obedience",
      dependencies: ["sit", "focus"],
      ageGateWeeks: 4,
      steps: [
        { title: "Catch and reward 3 seconds", successCriteria: "Holds sit-stay 3 seconds with handler at arm's length 8 of 10 reps (beginner)", sessionsRequired: 3, completedSessions: 0 },
        { title: "Increase distance and duration", successCriteria: "Holds stay 15 seconds with handler 6 feet away, controlled environment (medium)", sessionsRequired: 4, completedSessions: 0 },
        { title: "Surprise stay, uncontrolled environment", successCriteria: "Holds stay through a squeaky toy rolling by, other toys, or people (hard)", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "Stay — 1:45 min mark", type: "video", url: "https://www.youtube.com/watch?v=GAziMECDxD0&t=313s", publisher: "Dog Rules reference" },
        { title: "Stay with distraction — 2 min and 4:45 min marks", type: "video", url: "https://www.youtube.com/watch?v=2-_rxxKxseU", publisher: "Dog Rules reference" },
        { title: "How to Teach Your Dog to Stay", type: "article", url: "https://www.akc.org/expert-advice/training/teach-your-dog-to-stay/", publisher: "AKC" },
      ],
      why: "Week 4 command per the real training schedule. Layers duration on top of a reliable sit and the focus needed to hold it, and becomes the foundation for place and advanced recall.",
    },
    {
      id: "wait",
      title: "Wait",
      track: "obedience",
      dependencies: ["impulse-control", "sit"],
      steps: [
        { title: "Wait at bowl", successCriteria: "Waits without breaking while bowl is set down, released on cue", sessionsRequired: 2, completedSessions: 0 },
        { title: "Wait at door", successCriteria: "Waits at threshold while door opens fully, released on cue", sessionsRequired: 3, completedSessions: 0 },
        { title: "Wait at car / curb", successCriteria: "Waits before exiting car or crossing curb until released", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach Your Dog to Wait at Doorways", type: "article", url: "https://www.akc.org/expert-advice/training/teach-your-dog-to-wait-at-doorways/", publisher: "AKC" },
        { title: "Training your dog to 'wait' and 'stay'", type: "plan", url: "https://www.whole-dog-journal.com/behavior/training-your-dog-to-wait-and-stay/", publisher: "Whole Dog Journal" },
        { title: "Wait command training", type: "video", url: "https://www.youtube.com/results?search_query=teach+dog+wait+at+door+command", publisher: "YouTube training library" },
      ],
      why: "A lighter-weight cousin of stay focused on momentary impulse control at thresholds (doors, cars, curbs), so it depends on impulse control and a working sit rather than full stay duration.",
    },
    {
      id: "heel",
      title: "Heel",
      track: "obedience",
      dependencies: ["loose-leash", "focus"],
      steps: [
        { title: "Position at the leg indoors", successCriteria: "Holds heel position for 10 steps indoors with lure", sessionsRequired: 3, completedSessions: 0 },
        { title: "Fade lure, add turns", successCriteria: "Maintains heel position through 2 turns without a lure", sessionsRequired: 4, completedSessions: 0 },
        { title: "Proof outdoors with distraction", successCriteria: "Holds heel position for 30 feet past a mild distraction", sessionsRequired: 5, completedSessions: 0 },
      ],
      sources: [
        { title: "Teach a Dog to Heel: How to Train a Dog to Walk Beside You", type: "article", url: "https://www.akc.org/expert-advice/training/heeling-teach-dog-walk/", publisher: "AKC" },
        { title: "Heel position training", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+heel+position+training", publisher: "Kikopup" },
        { title: "Training games for dogs", type: "article", url: "https://www.akc.org/expert-advice/training/training-games-for-dogs/", publisher: "AKC" },
      ],
      why: "A precise, structured version of loose leash walking that also requires strong focus, since the dog must hold a specific position relative to the handler rather than just avoid pulling.",
    },
    {
      id: "touch",
      title: "Touch (hand target)",
      track: "obedience",
      dependencies: ["marker-word", "food-lure"],
      steps: [
        { title: "Nose to palm", successCriteria: "Touches nose to open palm 8 of 10 reps", sessionsRequired: 2, completedSessions: 0 },
        { title: "Add verbal cue and distance", successCriteria: "Moves 3 feet to touch palm on cue alone", sessionsRequired: 3, completedSessions: 0 },
        { title: "Use touch to redirect", successCriteria: "Redirects away from a mild distraction using touch cue 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach Your Dog to Nose Target or 'Touch'", type: "article", url: "https://www.akc.org/expert-advice/training/teach-dog-nose-target-touch/", publisher: "AKC" },
        { title: "Hand targeting foundation", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+hand+targeting+touch+training", publisher: "Kikopup" },
        { title: "Positive reinforcement training basics", type: "article", url: "https://www.humanesociety.org/resources/positive-reinforcement-training", publisher: "Humane Society" },
      ],
      why: "A simple, high-value target behavior built on marker timing and lure mechanics that becomes the building block for fetch (targeting an object) and for redirecting attention in distracting environments.",
    },
    {
      id: "place",
      title: "Mat Training (Place)",
      track: "obedience",
      dependencies: ["down", "stay"],
      ageGateWeeks: 6,
      steps: [
        { title: "Settle on the mat", successCriteria: "Reaches a relaxed one-hip position on the mat and gets kibble; if the dog leaves the mat, pick it up and restart from the last spot", sessionsRequired: 3, completedSessions: 0 },
        { title: "Send from a short distance", successCriteria: "Runs to mat and settles from 6 feet away on cue", sessionsRequired: 4, completedSessions: 0 },
        { title: "Hold place through household activity", successCriteria: "Stays on mat through doorbell or meal prep until released", sessionsRequired: 5, completedSessions: 0 },
      ],
      sources: [
        { title: "Dr. Karen Overall Protocol for Relaxation (PDF)", type: "plan", url: "https://journeydogtraining.com/wp-content/uploads/2017/07/ProtocolforRelaxation.pdf", publisher: "Journey Dog Training" },
        { title: "Protocol Day 0 / Day 1 / Day 2 / Day 3", type: "video", url: "https://www.youtube.com/watch?v=wJGHOhbmjac&t=259s", publisher: "Dog Rules reference" },
        { title: "How To Teach Your Dog To Go to Their Place", type: "article", url: "https://www.akc.org/expert-advice/training/teaching-go-to-your-place/", publisher: "AKC" },
      ],
      why: "Week 6-8 command per the real training schedule, and officially the start of the formal training program per Dog.xlsx. Combines a settled down with stay-level duration on a specific target.",
    },
    {
      id: "speak",
      title: "Speak",
      track: "obedience",
      dependencies: ["marker-word"],
      steps: [
        { title: "Capture and mark a bark", successCriteria: "Marks and rewards a spontaneous single bark 5 times in a session", sessionsRequired: 2, completedSessions: 0 },
        { title: "Add verbal cue", successCriteria: "Barks once within 3 seconds of cue 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "Bark training scenarios (Zak George)", type: "video", url: "https://www.youtube.com/watch?v=s0A9SpCdRZg", publisher: "Dog Rules reference" },
        { title: "How to get your dog to stop barking", type: "article", url: "https://www.humanesociety.org/resources/how-get-your-dog-stop-barking", publisher: "Humane Society" },
        { title: "'Speak!' Training Your Dog to Bark on Command", type: "article", url: "https://www.akc.org/expert-advice/training/train-your-dog-to-speak/", publisher: "AKC" },
      ],
      why: "Marked 'pending update' in the household's training notes — an advanced trick to revisit once core commands are solid. Putting barking on a deliberate cue relies only on solid marker timing, and sets up quiet as a natural next step.",
    },
    {
      id: "quiet",
      title: "Quiet",
      track: "obedience",
      dependencies: ["speak"],
      steps: [
        { title: "Mark silence after a bark", successCriteria: "Rewards 2 seconds of silence immediately following a cued bark 8 of 10 reps", sessionsRequired: 2, completedSessions: 0 },
        { title: "Add verbal cue and extend duration", successCriteria: "Stops barking within 3 seconds of cue and holds silence 10 seconds", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "How to get your dog to stop barking", type: "article", url: "https://www.humanesociety.org/resources/how-get-your-dog-stop-barking", publisher: "Humane Society" },
        { title: "Bark training scenarios (Zak George) — covers toys, boredom, waiting for treats, doorbell, and crate barking", type: "video", url: "https://www.youtube.com/watch?v=s0A9SpCdRZg", publisher: "Dog Rules reference" },
        { title: "Expert Tips to Help Curb Excessive Dog Barking", type: "article", url: "https://www.akc.org/expert-advice/training/curb-excessive-dog-barking/", publisher: "AKC" },
      ],
      why: "Quiet is easiest to train once barking is already on a cue via speak, since the handler can prompt a bark and then reward the stop rather than waiting for random barking to interrupt.",
    },
    {
      id: "shake",
      title: "Shake (Paw)",
      track: "obedience",
      dependencies: ["marker-word", "food-lure"],
      ageGateWeeks: 6,
      steps: [
        { title: "Capture the paw lift", successCriteria: "Paws at closed hand and gets marked/rewarded 8 of 10 reps", sessionsRequired: 2, completedSessions: 0 },
        { title: "Add verbal cue", successCriteria: "Offers paw on cue alone without hand presented first", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "How To Teach a Dog to Shake Hands", type: "article", url: "https://www.akc.org/expert-advice/training/how-to-teach-your-dog-to-shake-hands/", publisher: "AKC" },
        { title: "Teach shake without hand manipulation", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+teach+dog+shake+paw+trick", publisher: "Kikopup" },
        { title: "Positive reinforcement training basics", type: "article", url: "https://www.humanesociety.org/resources/positive-reinforcement-training", publisher: "Humane Society" },
      ],
      why: "A simple capture-and-lure trick that reinforces clean marker timing and lure fading, giving an easy early win once the mechanical foundations are in place.",
    },
    {
      id: "spin",
      title: "Spin",
      track: "obedience",
      dependencies: ["food-lure", "focus"],
      steps: [
        { title: "Lure a full circle", successCriteria: "Follows lure through a 360-degree turn 8 of 10 reps", sessionsRequired: 2, completedSessions: 0 },
        { title: "Fade lure, add cue, both directions", successCriteria: "Spins in either direction on verbal cue without a visible lure", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach Your Dog to Spin Around", type: "article", url: "https://www.akc.org/expert-advice/training/teach-your-dog-to-spin-around/", publisher: "AKC" },
        { title: "Spin trick training", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+teach+dog+spin+trick", publisher: "Kikopup" },
        { title: "Advanced dog tricks", type: "article", url: "https://www.akc.org/expert-advice/training/advanced-dog-tricks/", publisher: "AKC" },
      ],
      why: "Builds directly on lure-following mechanics and requires sustained focus to complete a full circle without breaking off, making it a natural next trick once both are solid.",
    },
    {
      id: "roll-over",
      title: "Roll over",
      track: "obedience",
      dependencies: ["down", "food-lure"],
      ageGateWeeks: 6,
      steps: [
        { title: "Lure from down to side", successCriteria: "Follows lure from down into a side-lie 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
        { title: "Complete the roll", successCriteria: "Completes a full roll from lure with verbal cue paired", sessionsRequired: 3, completedSessions: 0 },
        { title: "Fade lure", successCriteria: "Rolls over on verbal cue alone 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach a Dog to Roll Over", type: "article", url: "https://www.akc.org/expert-advice/training/how-to-teach-a-dog-to-roll-over/", publisher: "AKC" },
        { title: "Roll over trick training", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+teach+dog+roll+over+trick", publisher: "Kikopup" },
        { title: "Advanced dog tricks", type: "article", url: "https://www.akc.org/expert-advice/training/advanced-dog-tricks/", publisher: "AKC" },
      ],
      why: "Starts from a settled down and uses the same lure-following skill as spin, just guided along the ground instead of in a circle, so a comfortable down is a prerequisite.",
    },
    {
      id: "play-dead",
      title: "Play dead",
      track: "obedience",
      dependencies: ["down"],
      steps: [
        { title: "Lure onto side from down", successCriteria: "Falls onto side from a down position 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
        { title: "Add cue and hold briefly", successCriteria: "Holds the side-lie 3 seconds on verbal cue before release word", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach Your Dog to Play Dead", type: "article", url: "https://www.akc.org/expert-advice/training/teach-your-dog-to-play-dead/", publisher: "AKC" },
        { title: "Play dead trick training", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+teach+dog+play+dead+trick", publisher: "Kikopup" },
        { title: "Advanced dog tricks", type: "article", url: "https://www.akc.org/expert-advice/training/advanced-dog-tricks/", publisher: "AKC" },
      ],
      why: "Explicitly requires a known down cue as the starting position before the side-lie and hold can be layered on top, per standard trick-training progression.",
    },
    {
      id: "fetch",
      title: "Fetch (Give)",
      track: "obedience",
      dependencies: ["touch", "impulse-control"],
      ageGateWeeks: 6,
      steps: [
        { title: "Chase and grab a tossed toy", successCriteria: "Chases and picks up a tossed toy 8 of 10 reps", sessionsRequired: 2, completedSessions: 0 },
        { title: "Bring toy back toward handler", successCriteria: "Returns toy to within arm's reach of handler 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
        { title: "Full fetch loop with release", successCriteria: "Completes toss-chase-return-release loop 5 times in a row without chasing", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach Your Dog to Fetch", type: "article", url: "https://www.akc.org/expert-advice/training/teach-your-dog-to-fetch/", publisher: "AKC" },
        { title: "Two-toy fetch training", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+teach+dog+fetch+two+toy+method", publisher: "Kikopup" },
        { title: "Training games for dogs", type: "article", url: "https://www.akc.org/expert-advice/training/training-games-for-dogs/", publisher: "AKC" },
      ],
      why: "Uses hand-targeting drive toward an object plus enough impulse control to bring the toy back rather than keep-away, making both prerequisite skills load-bearing for a clean return.",
    },
    {
      id: "retrieve",
      title: "Formal retrieve",
      track: "obedience",
      dependencies: ["fetch", "drop-it"],
      steps: [
        { title: "Hold and carry", successCriteria: "Holds a toy in mouth for 5 seconds while walking beside handler", sessionsRequired: 3, completedSessions: 0 },
        { title: "Deliver to hand", successCriteria: "Releases toy directly into handler's hand on cue 8 of 10 reps", sessionsRequired: 4, completedSessions: 0 },
        { title: "Retrieve a dropped item on request", successCriteria: "Picks up and delivers a named household item to hand 7 of 10 reps", sessionsRequired: 5, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach Your Dog to Fetch", type: "article", url: "https://www.akc.org/expert-advice/training/teach-your-dog-to-fetch/", publisher: "AKC" },
        { title: "Formal retrieve with hold and deliver", type: "video", url: "https://www.youtube.com/results?search_query=formal+retrieve+hold+and+deliver+dog+training", publisher: "YouTube training library" },
        { title: "Positive reinforcement training basics", type: "article", url: "https://www.humanesociety.org/resources/positive-reinforcement-training", publisher: "Humane Society" },
      ],
      why: "Extends casual fetch into a controlled hold-and-deliver behavior, which requires the clean release taught in drop it so the dog gives up the item into a hand instead of dropping it on the ground.",
    },
    {
      id: "advanced-recall",
      title: "Advanced recall",
      track: "obedience",
      dependencies: ["recall-foundation", "stay"],
      steps: [
        { title: "Recall away from a stay", successCriteria: "Breaks a stay and recalls immediately on cue 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
        { title: "Recall with moderate distraction", successCriteria: "Recalls past a person, toy, or food distraction at 10 feet", sessionsRequired: 4, completedSessions: 0 },
        { title: "Long-line recall outdoors", successCriteria: "Recalls from 30+ feet on a long line in a new outdoor location 8 of 10 reps", sessionsRequired: 5, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Train Your Dog to Come When Called: Step-by-Step Recall", type: "article", url: "https://www.akc.org/expert-advice/training/reliable-recalls-how-to-train-your-dog-to-come-when-called/", publisher: "AKC" },
        { title: "Advanced recall with distraction and distance", type: "video", url: "https://www.youtube.com/results?search_query=zak+george+advanced+recall+training+distractions", publisher: "Zak George" },
        { title: "Why a reliable recall is so important", type: "plan", url: "https://www.whole-dog-journal.com/training/leash_training/why-a-reliable-recall-is-so-important/", publisher: "Whole Dog Journal" },
      ],
      why: "Adds real distraction and distance on top of recall foundation, and requires stay so the dog has practice holding position under mild arousal before being asked to break it on cue.",
    },
    {
      id: "emergency-recall",
      title: "Emergency recall",
      track: "obedience",
      dependencies: ["recall-foundation", "advanced-recall"],
      steps: [
        { title: "Condition a unique emergency cue", successCriteria: "Orients and sprints to handler on the special cue paired with a jackpot reward 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
        { title: "Proof under high distraction", successCriteria: "Responds to emergency cue within 2 seconds during active play or around another dog", sessionsRequired: 4, completedSessions: 0 },
        { title: "Randomized real-world tests", successCriteria: "Responds successfully to 5 unannounced real-world tests across different locations", sessionsRequired: 5, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach Your Dog the Emergency Recall", type: "article", url: "https://www.preventivevet.com/dogs/teach-your-dog-the-emergency-recall-come", publisher: "Preventive Vet" },
        { title: "Emergency recall conditioning", type: "video", url: "https://www.youtube.com/results?search_query=emergency+recall+training+dog+jackpot+cue", publisher: "YouTube training library" },
        { title: "Reliable Recall: Teaching Your Dog to Always Come When Called", type: "article", url: "https://www.akc.org/expert-advice/training/reliable-recall-train-dogs-to-come-when-called/", publisher: "AKC" },
      ],
      why: "Reserves a separate, never-poisoned cue with maximum reinforcement history for true emergencies, so it depends on both recall foundation and advanced-recall being solid before adding a dedicated life-or-death cue on top.",
    },
    {
      id: "crate-training",
      title: "Crate training",
      track: "handling",
      dependencies: [],
      ageGateWeeks: 1,
      steps: [
        { title: "Positive introduction", successCriteria: "Sniffs and explores the open crate with treats/toys inside, no door closing yet", sessionsRequired: 3, completedSessions: 0 },
        { title: "Close the door briefly", successCriteria: "Accepts the door slowly closed (not locked) while treats feed through, 15 min or less", sessionsRequired: 4, completedSessions: 0 },
        { title: "Build duration", successCriteria: "Settles calmly in crate for 15 min - 1 hr after exercise, low frequency of longer stretches", sessionsRequired: 5, completedSessions: 0 },
      ],
      sources: [
        { title: "Crate Training (Zak George)", type: "video", url: "https://www.youtube.com/watch?v=hesi8WxLWVE", publisher: "Dog Rules reference" },
        { title: "Crate training — other resource, 10:00 mark", type: "video", url: "https://www.youtube.com/watch?v=R0vTyXCP5vY", publisher: "Zak George" },
        { title: "Puppy Potty Training Tips (crate section)", type: "article", url: "https://www.akc.org/expert-advice/training/potty-training-puppy-tips/", publisher: "AKC" },
      ],
      why: "Major rule: the crate is never a punishment. Always exercise first, keep early sessions between 15 minutes and 1 hour, and it's fine to run more frequent short stretches while building up duration. This is the direct foundation for every alone-time milestone in Section 4 of the household knowledge base.",
    },
    {
      id: "settle-alone-time",
      title: "Settle / home alone",
      track: "confidence",
      dependencies: ["crate-training"],
      ageGateWeeks: 8,
      steps: [
        { title: "Short departures", successCriteria: "Settles calmly for 15-30 min departures with no crying at the door", sessionsRequired: 4, completedSessions: 0 },
        { title: "1-2 hour stretch", successCriteria: "Handles a 1-2 hour departure (e.g. a gym class) calmly, logged in the alone-time tracker", sessionsRequired: 3, completedSessions: 0 },
        { title: "3-4 hour stretch", successCriteria: "Handles a 3-4 hour departure calmly ahead of the BYU/Notre Dame tailgate (10/17) target", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "Puppy Training Timeline (alone-time conditioning)", type: "article", url: "https://www.akc.org/expert-advice/training/puppy-training-timeline-teaching-good-behavior-before-its-too-late/", publisher: "AKC" },
        { title: "Dr. Karen Overall Protocol for Relaxation (PDF)", type: "plan", url: "https://journeydogtraining.com/wp-content/uploads/2017/07/ProtocolforRelaxation.pdf", publisher: "Journey Dog Training" },
      ],
      why: "Listed as 'Settle (separation anxiety)' in the 8-16 week training schedule, and directly tied to the household's real calendar: several hours alone for September concerts, ~4 hours for the 10/17 BYU/Notre Dame tailgate, a full evening for Mammoth hockey, and a full day (6-8 hrs) for late-December ski trips. Log real achieved durations in the alone-time tracker so the app can flag gaps against upcoming commitments before they happen.",
    },
    {
      id: "no-jumping",
      title: "No jumping on people",
      track: "obedience",
      dependencies: ["impulse-control"],
      ageGateWeeks: 8,
      steps: [
        { title: "Withhold attention", successCriteria: "Handler withholds all petting/attention until all four paws are on the ground", sessionsRequired: 3, completedSessions: 0 },
        { title: "Proof with greetings", successCriteria: "Greets a familiar person without jumping 8 of 10 times", sessionsRequired: 4, completedSessions: 0 },
        { title: "Proof with strangers", successCriteria: "Does not jump on an unfamiliar person during a greeting", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "Dog Should Not Jump on People (Zak George)", type: "video", url: "https://www.youtube.com/watch?v=49A12LPsE8M", publisher: "Dog Rules reference" },
        { title: "No Jumping training", type: "video", url: "https://www.youtube.com/watch?v=7P1DgDED23o", publisher: "Zak George" },
      ],
      why: "Listed as 'Not jumping on strangers' in the 8-16 week training schedule. Dogs want attention for greeting — taking that away until paws are down is what teaches the alternative.",
    },
    {
      id: "grooming-desensitizing",
      title: "Grooming desensitizing",
      track: "handling",
      dependencies: [],
      ageGateWeeks: 1,
      steps: [
        { title: "Intro to grooming tools", successCriteria: "Calm around brush, nail grinder/clippers, and dryer without handling yet", sessionsRequired: 3, completedSessions: 0 },
        { title: "First grooming session", successCriteria: "Accepts a full brush-out and nail check calmly", sessionsRequired: 3, completedSessions: 0 },
      ],
      sources: [
        { title: "Intro to grooming — 9 min mark", type: "video", url: "https://www.youtube.com/watch?v=0c-IjjzmS0E&list=PLMssKIjsDxXl_ZXQgcHlEY_fC-yL5P76N&index=3", publisher: "Dog Rules reference" },
        { title: "First grooming session", type: "video", url: "https://www.youtube.com/watch?v=koOCGuRFF0I", publisher: "Dog Rules reference" },
      ],
      why: "Desensitizing to grooming tools early avoids fights over nail trims and brushing for the rest of the dog's life — worth starting well before the monthly nail-trim/bi-monthly grooming cadence kicks in.",
    },
    {
      id: "frisbee",
      title: "Frisbee",
      track: "obedience",
      dependencies: ["fetch"],
      ageGateWeeks: 6,
      steps: [
        { title: "Chase a rolled disc", successCriteria: "Chases and grabs a rolled (not thrown) frisbee 8 of 10 reps", sessionsRequired: 2, completedSessions: 0 },
        { title: "Short thrown catches", successCriteria: "Catches a short, low throw and returns it", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "How to Teach Your Dog to Fetch", type: "article", url: "https://www.akc.org/expert-advice/training/teach-your-dog-to-fetch/", publisher: "AKC" },
      ],
      why: "Week 6-8 command per the real training schedule, building directly on Fetch. Griz already loves frisbee, so this doubles as a shared enrichment activity once the puppy is ready.",
    },
    {
      id: "greeting-others",
      title: "Greeting others",
      track: "socialization",
      dependencies: ["no-jumping", "impulse-control"],
      ageGateWeeks: 6,
      steps: [
        { title: "Greet a calm familiar person", successCriteria: "Sits or stands calmly for a greeting from a known person, no jumping", sessionsRequired: 3, completedSessions: 0 },
        { title: "Greet a new person", successCriteria: "Meets a new person calmly with all four paws down", sessionsRequired: 4, completedSessions: 0 },
      ],
      sources: [
        { title: "Puppy Socialization: Why, When, and How to Do It Right", type: "article", url: "https://www.akc.org/expert-advice/training/puppy-socialization/", publisher: "AKC" },
      ],
      why: "Week 6-8 command per the real training schedule. Combines the no-jumping rule with impulse control specifically for the moment guests or strangers approach.",
    },
  ] as Array<Omit<Milestone, "dogIds" | "status">>).map((milestone) => ({ ...milestone, dogIds: ["puppy"], status: "locked" as const })),
];

export const healthEvents: HealthEvent[] = [
  {
    id: "pickup-day",
    dogId: "puppy",
    title: "Pickup day — Ruby Doodles Louisiana",
    date: "2026-08-01",
    kind: "weight",
    notes: "Mid-afternoon pickup. Confirm name, sex, birthday, microchip, and get breeder health records. First weigh-in today.",
  },
  {
    id: "first-vet-visit",
    dogId: "puppy",
    title: "First vet appointment — Canyons Vet",
    date: "2026-08-03",
    kind: "vet",
    notes: "2:00 PM. Bring breeder health records. Confirm vaccine schedule and set booster dates.",
  },
  { id: "heartworm", dogId: "griz", title: "Heartworm prevention", date: "2026-07-20", kind: "medication", notes: "Monthly prevention, per care sheet cadence." },
  { id: "groom", dogId: "griz", title: "Grooming reset", date: "2026-08-07", kind: "grooming", notes: "Brush, nail check, ear check." },
];

export const journalEntries: JournalEntry[] = [
  {
    id: "entry-pickup-prep",
    dogIds: ["puppy"],
    date: "2026-07-25",
    title: "Pickup week prep checklist",
    text: "Crate and pen set up, potty spot picked out near the door, breeder paperwork folder ready, first vet appointment (8/3, 2:00 PM, Canyons Vet) on the calendar. Plan for a parallel-walk introduction with Griz once the puppy has settled in for a few days rather than day one.",
    tags: ["prep", "pickup", "planning"],
    mood: "steady",
  },
];

function slug(title: string) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function exposureItem(
  category: ExposureItem["category"],
  title: string,
  overrides: Partial<Pick<ExposureItem, "status" | "log" | "dogIds">> = {},
): ExposureItem {
  return {
    id: `${category}-${slug(title)}`,
    category,
    title,
    dogIds: overrides.dogIds ?? ["puppy"],
    status: overrides.status ?? "not-started",
    log: overrides.log ?? [],
  };
}

const socializationList = [
  "Children",
  "Men",
  "Women",
  "Tall people",
  "Beards",
  "Umbrellas",
  "Wheelchairs",
  "Scooters",
  "Skateboards",
  "Vacuum",
  "Blender",
  "Hair dryer",
  "Doorbell",
  "Thunder",
  "Fireworks",
  "Rain",
  "Snow",
  "Wind",
  "Cars",
  "Buses",
  "Motorcycles",
  "Livestock",
  "Cats",
  "Birds",
  "Other dogs",
  "Restaurants",
  "Stores",
  "Parks",
  "Vet clinic",
  "Groomer",
  "Elevator",
  "Escalator",
  "Metal flooring",
  "Wood flooring",
  "Concrete flooring",
  "Grass",
  "Sand",
  "Water",
  "Bridges",
  "Stairs",
];

const confidenceList = [
  "Balance discs",
  "Wobble board",
  "Tunnel",
  "Boxes",
  "Plastic bags",
  "Tarps",
  "Car rides",
  "Camping",
  "Kayak",
  "Hotel stays",
  "Elevator",
  "Busy sidewalks",
];

const handlingList = [
  "Touch ears",
  "Touch paws",
  "Brush",
  "Open mouth",
  "Lift lips",
  "Tail handling",
  "Nail grinder",
  "Nail clippers",
  "Bath",
  "Hair dryer",
  "Tooth brushing",
  "Eye cleaning",
  "Medication practice",
  "Harness",
  "Collar",
  "Cone",
];

// All start "not-started" with an empty log — none of this has happened yet
// since the puppy isn't picked up until 8/1/26. Log real entries as they occur.
export const exposureItems: ExposureItem[] = [
  ...socializationList.map((title) => exposureItem("socialization", title)),
  ...confidenceList.map((title) => exposureItem("confidence", title)),
  ...handlingList.map((title) => exposureItem("handling", title)),
];

// Empty until the puppy is actually picked up (8/1/26) and the two dogs meet —
// no real relationship data exists yet. Log the first parallel walk here once it happens.
export const relationshipLogs: RelationshipLog[] = [];

// General food-safety shelf-life defaults (days, refrigerated/pantry as typical
// for the category) — a starting point the Meals view uses to suggest an
// expiration date from a purchase date; always user-adjustable per item.
export const shelfLifeDefaultsDays: Record<InventoryCategory, number> = {
  produce: 7,
  dairy: 14,
  meat: 3,
  seafood: 2,
  eggs: 21,
  bread: 7,
  frozen: 90,
  "pantry-staple": 365,
  leftovers: 4,
  other: 14,
};

// Meal planning starts empty — no dietary preferences, target meal count, or
// recurring favorites were specified, so there's nothing real to seed yet.
export const meals: Meal[] = [];
export const recipeIngredients: RecipeIngredient[] = [];
export const inventory: InventoryItem[] = [];
export const groceryList: GroceryListItem[] = [];

export const feedbackLoopRules: FeedbackLoopRule[] = [
  {
    id: "task-completion",
    trigger: "Checkboxes, ratings, durations, accidents, barking, fear, guarding, and session counts",
    route: "algorithm",
    cadence: "instant",
    updates: [
      "Task streaks and overdue state",
      "Milestone step progress",
      "Readiness scores",
      "Tomorrow's optional workload",
      "Relationship and confidence trend lines",
    ],
    costControl: "Runs entirely in local code with no API call.",
  },
  {
    id: "health-records",
    trigger: "Vaccines, vet appointments, medications, weight entries, allergies, and insurance updates",
    route: "algorithm",
    cadence: "instant",
    updates: [
      "Static calendar",
      "Health alerts",
      "Age and vaccine gates",
      "Growth chart",
      "Blocked/unblocked health-dependent milestones",
    ],
    costControl: "Rules and date math handle the update; AI is only used for optional summarization of long vet notes.",
  },
  {
    id: "free-text-notes",
    trigger: "Journal text, task comments, copied vet instructions, or multi-day behavior descriptions",
    route: "genAI",
    cadence: "nightly",
    updates: [
      "Short trend summary",
      "Suggested tags",
      "Possible explanation for schedule changes",
      "Questions to ask the vet or trainer",
    ],
    costControl: "Batch once per day, summarize only new text, cap the prompt, and store the summary so it is not regenerated.",
  },
  {
    id: "weekly-review",
    trigger: "Seven days of structured logs or a manual weekly review request",
    route: "genAI",
    cadence: "weekly",
    updates: [
      "Weekly coaching note",
      "Plain-English explanation of adaptive changes",
      "Top three focus areas",
      "Suggested workload adjustment",
    ],
    costControl: "One compact request per week using rollups instead of raw history.",
  },
  {
    id: "safety-flags",
    trigger: "Bite, injury, severe fear, repeated guarding, medication reaction, or concerning vet note",
    route: "human-review",
    cadence: "instant",
    updates: [
      "Health or behavior alert",
      "Pause risky milestones",
      "Prompt to contact veterinarian or qualified trainer",
    ],
    costControl: "No model needed before the alert; AI can draft a summary for the professional only if requested.",
  },
  {
    id: "future-video",
    trigger: "Uploaded training or play video",
    route: "genAI",
    cadence: "on-demand",
    updates: [
      "Marker timing observation",
      "Engagement notes",
      "Body-language checklist",
      "Suggested next rep difficulty",
    ],
    costControl: "Never automatic. Run only on short clips selected by the user.",
  },
];

// ---------------------------------------------------------------------------
// Household calendar: recurring commitments, one-off life events, and the
// full football schedule. Source: docs/knowledge/puppy-life-knowledge.md
// sections 3-6. All dates/times are the real 2026 household schedule.
// ---------------------------------------------------------------------------

// Kickoff times are often "TBA" or flex windows this far out — only clean
// "H:MM AM/PM" strings (optionally with a trailing parenthetical like "(Fri)")
// become a structured startTime; everything else stays descriptive-only via notes.
const CLEAN_TIME = /^~?\d{1,2}:\d{2}\s*(AM|PM)(\s*\([^)]*\))?$/i;

function footballGame(
  id: string,
  team: "Georgia" | "Clemson",
  opponent: string,
  date: string,
  timeLabel: string,
  status: CalendarEvent["status"],
  importance: CalendarEvent["importance"],
  notes: string,
): CalendarEvent {
  const clean = CLEAN_TIME.test(timeLabel);
  return {
    id,
    title: `${team} ${opponent}`,
    category: "sports",
    kind: "one-off",
    date,
    windowLabel: "",
    startTime: clean ? timeLabel.replace(/^~/, "") : undefined,
    aloneTimeRequired: "no",
    status,
    importance,
    notes: clean ? notes : `${timeLabel}. ${notes}`,
  };
}

export const calendarEvents: CalendarEvent[] = [
  // Recurring weekly commitments
  {
    id: "gym-concert-series",
    title: "Gym — concert series",
    category: "sports",
    kind: "recurring",
    recurrence: { frequency: "weekly", interval: 1, daysOfWeek: ["wednesday"], startDate: "2026-08-01", endDate: "2026-09-07" },
    windowLabel: "",
    startTime: "6:00 PM",
    durationHours: 1.25,
    aloneTimeRequired: "all",
    status: "confirmed",
    attendees: ["andrew", "bree"],
    notes:
      "Through Labor Day (9/7/26). Default: go together — a ~1-1.25 hr window is inside the crate-trained short-alone-time tier (no Rover needed). If schedules split some weeks, see the household overlap policy: stagger start times ~30-45 min so one person is always home, rather than both being out the full window.",
  },
  {
    id: "gym-hot-dogs",
    title: "Gym — \"Hot Dogs\"",
    category: "sports",
    kind: "recurring",
    recurrence: { frequency: "weekly", interval: 1, daysOfWeek: ["monday"], startDate: "2026-08-01", endDate: "2026-09-07" },
    windowLabel: "",
    startTime: "5:30 PM",
    durationHours: 1.25,
    aloneTimeRequired: "all",
    status: "confirmed",
    attendees: ["andrew", "bree"],
    notes:
      "Through Labor Day (9/7/26). Same overlap policy as the Wednesday concert-series class — go together by default; stagger if a given Monday doesn't allow both to leave at once.",
  },
  {
    id: "andrew-volleyball",
    title: "Andrew's volleyball",
    category: "sports",
    kind: "recurring",
    recurrence: { frequency: "weekly", interval: 1, daysOfWeek: ["tuesday"], startDate: "2026-08-01" },
    windowLabel: "estimated — confirm exact time",
    durationHours: 2.5,
    aloneTimeRequired: "no",
    status: "placeholder",
    attendees: ["andrew"],
    notes:
      "~2-3 hr blocks. Exact schedule to be uploaded. Bree is solo with both dogs during this window — good slot for her personal downtime once the puppy settles, or a quieter training/relationship-building evening early on.",
  },
  {
    id: "curling",
    title: "Curling",
    category: "sports",
    kind: "recurring",
    recurrence: { frequency: "weekly", interval: 1, daysOfWeek: ["thursday"], startDate: "2026-08-01" },
    windowLabel: "starts fall 2026, exact date TBD",
    startTime: "8:30 PM",
    endTime: "11:00 PM",
    durationHours: 2.5,
    aloneTimeRequired: "all",
    status: "placeholder",
    attendees: ["andrew", "bree"],
    notes:
      "League start date not yet set. Treated as a shared couple activity (2.5 hrs, evening) — inside the medium alone-time tier once logged readiness supports it; no Rover needed if the puppy is already hitting 3-4 hr solo by fall.",
  },
  {
    id: "andrew-personal-time",
    title: "Andrew — personal time",
    category: "downtime",
    kind: "recurring",
    recurrence: { frequency: "weekly", interval: 1, daysOfWeek: ["tuesday"], startDate: "2026-08-01" },
    windowLabel: "estimated — confirm day/time, during Bree's coverage of Andrew's volleyball window",
    durationHours: 2,
    aloneTimeRequired: "no",
    status: "placeholder",
    attendees: ["andrew"],
    notes:
      "Placeholder slot for Spanish practice, vibe-coding, or other solo hobbies. Proposed default: Tuesday evenings work themselves out since Andrew is already out at volleyball — this block is really about protecting a second, at-home slot later in the week (e.g. a weekend afternoon) once the puppy's routine settles. Adjust day/time to whatever actually sticks.",
  },
  {
    id: "bree-personal-time",
    title: "Bree — personal time",
    category: "downtime",
    kind: "recurring",
    recurrence: { frequency: "weekly", interval: 1, daysOfWeek: ["tuesday"], startDate: "2026-08-01" },
    windowLabel: "estimated — confirm day/time, while Andrew is at volleyball",
    durationHours: 2,
    aloneTimeRequired: "no",
    status: "placeholder",
    attendees: ["bree"],
    notes:
      "Placeholder slot for art, house projects, or other solo hobbies — uses the Tuesday window Andrew is already out for volleyball. A second slot (e.g. a weekend morning) is worth adding once the together-time and nighttime routine settle into a fixed pattern.",
  },

  // One-off life events
  {
    id: "september-concerts",
    title: "September concerts",
    category: "entertainment",
    kind: "one-off",
    windowLabel: "mid-to-late September 2026, evening, date TBD",
    durationHours: 3,
    aloneTimeRequired: "all",
    status: "placeholder",
    roverVisits: 1,
    prepSteps: [
      "Potty walk ~30 min before leaving",
      "Pick up the water bowl ~1 hr before departure to cut down on mid-outing accidents",
      "Stuff and freeze a Kong, crate the puppy in the hardwood-floor room (easiest cleanup)",
      "Keep Griz in a separate room or gated area from the crate rather than free-roaming with a stressed puppy",
    ],
    roverInstructions: [
      "Arrive around the halfway point of the outing (~1.5 hrs in)",
      "Leash the puppy out to the usual potty spot and wait for a full elimination",
      "Refresh water, 10-15 min of low-key play or sniffing, then back in the crate with a fresh chew",
      "Text a quick note on accidents, barking, or anxiety",
    ],
    postSteps: ["Full decompression walk with both dogs", "Refresh water and clear any Kong remnants", "Log the outing in Alone-Time Readiness"],
    notes: "Several hours away (~3 hr estimate). Puppy's age at this point makes 1 Rover visit the right default — see Section 13 coverage tiers. Exact dates pending.",
  },
  {
    id: "comedy-shows",
    title: "Comedy shows",
    category: "entertainment",
    kind: "one-off",
    windowLabel: "mid-to-late September 2026 onward, evening, date TBD",
    durationHours: 3,
    aloneTimeRequired: "all",
    status: "placeholder",
    roverVisits: 1,
    prepSteps: [
      "Potty walk ~30 min before leaving",
      "Water bowl up ~1 hr before departure",
      "Stuffed frozen Kong in the crate, hardwood-floor room",
      "Griz kept separate from the crate for the first stretch",
    ],
    roverInstructions: ["One visit at the halfway mark: potty, fresh water, short play, fresh chew before re-crating", "Note any accidents or distress"],
    postSteps: ["Decompression walk on return", "Refresh water", "Log the outing"],
    notes:
      "Several hours away (~3 hr estimate). Optional depending on how alone-time readiness is tracking by then — if the puppy's already comfortably past 3 hrs solo, this one can drop to no Rover. Exact dates pending.",
  },
  {
    id: "byu-notre-dame-tailgate",
    title: "BYU vs. Notre Dame tailgate",
    category: "sports",
    kind: "one-off",
    date: "2026-10-17",
    windowLabel: "Kickoff TBA",
    durationHours: 4,
    aloneTimeRequired: "all",
    status: "confirmed",
    importance: "marquee",
    roverVisits: 1,
    prepSteps: [
      "Potty walk ~30 min before leaving",
      "Water bowl up ~1 hr before departure",
      "Stuffed frozen Kong, puppy crated in the hardwood-floor room",
      "Griz in a separate room/gated area, not free-roaming with the crate",
    ],
    roverInstructions: [
      "Visit around the 2-hr mark",
      "Potty break, fresh water, 15-20 min low-key play, fresh chew before re-crating",
      "Note any accidents, barking, or anxiety",
    ],
    postSteps: ["Full decompression walk with both dogs", "Refresh water and food", "Log the outing — this is the marquee readiness checkpoint"],
    notes:
      "LaVell Edwards Stadium, Provo. This is the ~4-hour alone-time milestone target — same date as Georgia @ Auburn and Clemson vs. Charleston Southern (stacked heavy week). Section 4's cross-reference found this date-driven target is more aggressive than typical age-based crating guidance for a puppy this age, so booking 1 Rover visit as a safety net is the realistic default rather than assuming readiness from the calendar alone.",
  },
  {
    id: "mammoth-hockey",
    title: "Utah Mammoth hockey games",
    category: "sports",
    kind: "one-off",
    windowLabel: "late October – early November 2026 onward, evening, specific games TBD",
    durationHours: 4.5,
    aloneTimeRequired: "all",
    status: "placeholder",
    roverVisits: 2,
    prepSteps: [
      "Potty walk ~30 min before leaving",
      "Water bowl up ~1-1.5 hrs before departure",
      "Stuffed frozen Kong, puppy crated in the hardwood-floor room",
      "Griz separated from the crate for the first stretch",
      "If the visit overlaps a scheduled meal, portion it out and label it for the sitter",
    ],
    roverInstructions: [
      "Visit 1 (~90 min in): potty, fresh water, short play, fresh chew",
      "Visit 2 (~3 hr in): potty, feed the labeled meal if one falls in this window, another short play session",
      "Note any accidents, barking, or anxiety on each visit",
    ],
    postSteps: ["Full decompression walk", "Refresh water", "Log the outing in Alone-Time Readiness"],
    notes:
      "Partial season ticket holder — drive + game + drive realistically runs ~4.5 hrs, a full-evening alone-time target. 2 Rover visits is the realistic default until logged readiness clears this window solo. Specific games attended still TBD.",
  },
  {
    id: "griz-hike-during-vet-visit",
    title: "Griz decompression hike (splits with puppy's vet visit)",
    category: "exercise",
    kind: "one-off",
    date: "2026-08-03",
    windowLabel: "",
    startTime: "2:00 PM",
    aloneTimeRequired: "no",
    status: "confirmed",
    attendees: ["bree"],
    notes:
      "Illustrates the general split pattern: when one dog has an appointment, the other doesn't have to sit it out. Bree takes Griz to the local hiking trail (puppy isn't cleared for trail exposure yet) while Andrew takes the puppy to the first vet appointment at Canyons Vet — two separate activities, two separate humans, same time window, instead of the whole household being tied to the vet trip. Swap people as makes sense on the actual day; the pattern is the point.",
  },
  {
    id: "mom-visiting",
    title: "Mom visiting",
    category: "family",
    kind: "one-off",
    date: "2026-09-23",
    windowLabel: "through Sept 26, multi-day visit",
    aloneTimeRequired: "no",
    status: "confirmed",
    notes: "Stay in Salt Lake City or day-trip distance only — no overnight travel or camping. Clemson @ Cal Fri 9/25 (8:30 PM MT) is a late TV game, no conflict with staying local.",
  },
  {
    id: "ski-days",
    title: "Ski days (as conditions allow)",
    category: "travel",
    kind: "one-off",
    windowLabel: "ski season, ~November 2026 – April 2027, variable — 45 min drive each way + 3-8 hrs on the mountain",
    durationHours: 6,
    aloneTimeRequired: "all",
    status: "placeholder",
    prepSteps: [
      "Decide the away-time tier before leaving: total away time (drive + ski + drive) under ~4.5 hrs needs no Rover once that alone-time milestone is cleared; ~4.5-7 hrs = 1 Rover visit; ~7-9.5 hrs = 2 visits",
      "Potty walk ~30 min before leaving",
      "Water bowl up ~1 hr before departure",
      "Stuffed frozen Kong, puppy crated in the hardwood-floor room",
      "Griz kept separate from the crate for the first stretch — he's fine solo for a full day if the trip runs long",
    ],
    roverInstructions: [
      "Time the visit(s) around the middle of however long you'll actually be gone — text the sitter your real ETA before leaving rather than a fixed clock time",
      "Standard visit: potty, fresh water, a meal if one falls in the window, 15-20 min play, fresh chew before re-crating",
      "Note accidents, appetite, and energy level",
    ],
    postSteps: [
      "Decompression walk with both dogs",
      "Refresh food and water",
      "Log the actual away-time (drive + ski + drive) in Alone-Time Readiness so future tiering stays accurate",
    ],
    notes:
      "SLC household — ~45 min drive each way to the mountain, skiing for as long as conditions and plans call for (as short as 3 hrs, up to a full 8-hour day), on nights, weekends, or a good-powder weekday — not a fixed December week. Total away time really ranges ~4.5-9.5 hrs including the drive, so treat the Rover call as a per-trip decision using the tiers above rather than one fixed plan.",
  },

  // Georgia Bulldogs 2026
  footballGame("uga-1", "Georgia", "vs. Tennessee State", "2026-09-05", "1:00 PM", "confirmed", "normal", "Home opener"),
  footballGame("uga-2", "Georgia", "vs. Western Kentucky", "2026-09-12", "10:45 AM", "confirmed", "normal", "Home"),
  footballGame("uga-3", "Georgia", "@ Arkansas", "2026-09-19", "10:00 AM", "confirmed", "normal", "Away"),
  footballGame("uga-4", "Georgia", "vs. Oklahoma", "2026-09-26", "Flex 1:30-2:30 PM or 4-6 PM", "placeholder", "normal", "Home, SEC"),
  footballGame("uga-5", "Georgia", "vs. Vanderbilt", "2026-10-03", "~10-11 AM window", "placeholder", "normal", "Home"),
  footballGame("uga-6", "Georgia", "@ Alabama", "2026-10-10", "Night, 4-6 PM window", "placeholder", "marquee", "Heavy/marquee week"),
  footballGame("uga-7", "Georgia", "vs. Auburn", "2026-10-17", "~1:30-2:30 PM window", "placeholder", "marquee", "Heavy week — same date as BYU/Notre Dame tailgate"),
  footballGame("uga-8", "Georgia", "vs. Florida (Atlanta)", "2026-10-31", "1:30 PM", "confirmed", "normal", "Rivalry, moved to Mercedes-Benz Stadium"),
  footballGame("uga-9", "Georgia", "@ Ole Miss", "2026-11-07", "Flex", "placeholder", "marquee", "Heavy/marquee week"),
  footballGame("uga-10", "Georgia", "vs. Missouri", "2026-11-14", "TBA", "placeholder", "normal", "Home"),
  footballGame("uga-11", "Georgia", "@ South Carolina", "2026-11-21", "TBA", "placeholder", "marquee", "Heavy week (Clemson @ Duke Fri 11/20 into this)"),
  footballGame("uga-12", "Georgia", "vs. Georgia Tech", "2026-11-28", "TBA", "placeholder", "marquee", "Rivalry, heavy week"),

  // Clemson Tigers 2026
  footballGame("clem-1", "Clemson", "@ LSU", "2026-09-05", "5:30 PM", "confirmed", "marquee", "College GameDay, Lane Kiffin's LSU debut"),
  footballGame("clem-2", "Clemson", "vs. Georgia Southern", "2026-09-12", "5:30 PM", "confirmed", "normal", "Home opener"),
  footballGame("clem-3", "Clemson", "vs. North Carolina", "2026-09-19", "10:00 AM", "confirmed", "normal", "Home"),
  footballGame("clem-4", "Clemson", "@ Cal", "2026-09-25", "8:30 PM (Fri)", "confirmed", "normal", "During mom's visit — late TV game, no conflict"),
  footballGame("clem-5", "Clemson", "vs. Miami", "2026-10-03", "TBA", "placeholder", "normal", "Home"),
  footballGame("clem-6", "Clemson", "vs. Charleston Southern", "2026-10-17", "TBA", "placeholder", "marquee", "Heavy week — stacked with Georgia/Auburn + BYU/Notre Dame"),
  footballGame("clem-7", "Clemson", "vs. Virginia Tech", "2026-10-24", "TBA", "placeholder", "normal", "Home — light week for Georgia (bye), but Clemson still plays"),
  footballGame("clem-8", "Clemson", "@ Florida State", "2026-10-31", "TBA", "placeholder", "normal", "Away"),
  footballGame("clem-9", "Clemson", "@ Syracuse", "2026-11-07", "TBA", "placeholder", "normal", "Away"),
  footballGame("clem-10", "Clemson", "vs. Georgia Tech", "2026-11-14", "TBA", "placeholder", "normal", "Home"),
  footballGame("clem-11", "Clemson", "@ Duke", "2026-11-20", "5:30 PM (Fri)", "confirmed", "marquee", "ACC title implications, heavy week into 11/21 Georgia @ South Carolina"),
  footballGame("clem-12", "Clemson", "vs. South Carolina", "2026-11-28", "TBA", "placeholder", "marquee", "Palmetto Bowl rivalry, heavy week"),
];

// Empty — no alone-time practice has happened yet since the puppy isn't
// picked up until 8/1/26. Log real entries via the app as training happens.
export const aloneTimeLogs: AloneTimeLog[] = [];
