import { Dog, FeedbackLoopRule, HealthEvent, JournalEntry, Milestone, Person, Task } from "./types";

export const people: Person[] = [
  {
    id: "andrew",
    name: "Andrew",
    color: "#2f6f64",
    taskIds: ["morning-potty", "name-recall"],
  },
  {
    id: "bree",
    name: "Bree",
    color: "#b46b55",
    taskIds: ["breakfast-reset", "parallel-walk", "handling"],
  },
];

export const dogs: Dog[] = [
  {
    id: "puppy",
    name: "New Puppy",
    breed: "Mixed breed",
    birthday: "2026-05-14",
    sex: "TBD",
    color: "#d6a657",
    weight: 12,
    expectedAdultWeight: 55,
    weightHistory: [
      { date: "2026-06-26", pounds: 9.8, notes: "Arrival baseline estimate" },
      { date: "2026-07-09", pounds: 12, notes: "Healthy appetite; confirm growth curve at booster visit" },
    ],
    microchip: "Pending",
    photo:
      "https://images.unsplash.com/photo-1593134257782-e89567b7718a?auto=format&fit=crop&w=700&q=80",
    veterinarian: "Primary vet",
    insurance: "To compare",
    breeder: "TBD",
    healthSummary: "Puppy schedule in progress; next booster and growth check are the highest-priority health items.",
    medicalHistory: ["Puppy wellness exam pending", "Vaccine booster scheduled"],
    allergies: [],
    medications: [],
    energy: 72,
    confidence: 54,
    fearfulness: 28,
    resourceGuarding: 12,
    dogFriendliness: 62,
    humanFriendliness: 70,
    noiseSensitivity: 38,
    favoriteRewards: ["Soft treats", "Kibble tosses", "Praise"],
    favoriteToys: ["Snuffle mat", "Rope", "Crinkle toy"],
    masteredCommands: ["Name recognition", "Marker word"],
    exerciseNeed: "Short age-appropriate sessions with naps protected",
    status: "puppy",
  },
  {
    id: "griz",
    name: "Griz",
    breed: "Adult dog",
    birthday: "2020-08-20",
    sex: "Male",
    color: "#6d7d8b",
    weight: 64,
    expectedAdultWeight: 64,
    weightHistory: [
      { date: "2026-05-01", pounds: 65, notes: "Spring baseline" },
      { date: "2026-07-09", pounds: 64, notes: "Stable adult weight" },
    ],
    microchip: "On file",
    photo:
      "https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=700&q=80",
    veterinarian: "Primary vet",
    insurance: "On file",
    breeder: "On file",
    healthSummary: "Adult maintenance plan: prevention, decompression exercise, grooming, and relationship support during puppy integration.",
    medicalHistory: ["Adult wellness records on file", "No active restrictions logged"],
    allergies: [],
    medications: ["Monthly prevention"],
    energy: 66,
    confidence: 78,
    fearfulness: 18,
    resourceGuarding: 18,
    dogFriendliness: 72,
    humanFriendliness: 84,
    noiseSensitivity: 24,
    favoriteRewards: ["Cheese", "Tug", "Release to sniff"],
    favoriteToys: ["Ball", "Tug toy", "Puzzle feeder"],
    masteredCommands: ["Sit", "Down", "Stay", "Recall", "Place"],
    exerciseNeed: "Daily decompression walk and enrichment",
    status: "adult",
  },
];

export const todayTasks: Task[] = [
  {
    id: "morning-potty",
    title: "Morning potty",
    category: "care",
    assignedTo: "andrew",
    time: "7:15 AM",
    duration: 5,
    priority: "essential",
    supplies: ["Treat pouch", "Leash"],
    setting: "outdoor",
    difficulty: 1,
    dogIds: ["puppy"],
    checklist: ["Outside", "Reward", "Pee", "Poop", "No accidents"],
    grizParticipation: "separate",
    notes: "Keep it boring, reward fast, log how quickly the puppy goes.",
  },
  {
    id: "breakfast-reset",
    title: "Breakfast + settle reset",
    category: "care",
    assignedTo: "bree",
    time: "7:45 AM",
    duration: 15,
    priority: "essential",
    supplies: ["Food", "Water", "Crate", "Puzzle feeder"],
    setting: "indoor",
    difficulty: 2,
    dogIds: ["puppy", "griz"],
    checklist: ["Separate meals", "Water refreshed", "Calm release", "Two-minute settle"],
    grizParticipation: "separate",
    notes: "Feed separately until relationship score stays above 80 for two weeks.",
  },
  {
    id: "name-recall",
    title: "Name + recall foundation",
    category: "training",
    assignedTo: "andrew",
    time: "12:15 PM",
    duration: 6,
    priority: "important",
    supplies: ["Soft treats", "Clicker or marker word"],
    setting: "indoor",
    difficulty: 2,
    dogIds: ["puppy"],
    checklist: ["Say name once", "Mark eye contact", "Treat at leg", "Five happy recalls"],
    grizParticipation: "managed",
    notes: "End before attention fades. Griz can practice place for parallel rewards.",
  },
  {
    id: "parallel-walk",
    title: "Parallel decompression walk",
    category: "relationship",
    assignedTo: "bree",
    time: "6:15 PM",
    duration: 18,
    priority: "important",
    supplies: ["Two leashes", "Treats", "Water"],
    setting: "outdoor",
    difficulty: 3,
    dogIds: ["puppy", "griz"],
    checklist: ["Start with distance", "Reward check-ins", "No shared toy", "Log body language"],
    grizParticipation: "yes",
    notes: "Keep dogs parallel, not face-to-face. Increase distance if either dog stiffens.",
  },
  {
    id: "handling",
    title: "Cooperative handling minis",
    category: "handling" as Task["category"],
    assignedTo: "bree",
    time: "8:30 PM",
    duration: 7,
    priority: "optional",
    supplies: ["Brush", "Treats", "Toothbrush"],
    setting: "indoor",
    difficulty: 2,
    dogIds: ["puppy"],
    checklist: ["Touch paws", "Lift lips", "Brush one stroke", "End with play"],
    grizParticipation: "managed",
    notes: "Consent-based pace. If the puppy withdraws twice, stop and make tomorrow easier.",
  },
];

export const milestones: Milestone[] = [
  {
    id: "marker-word",
    title: "Marker word",
    track: "obedience",
    dogIds: ["puppy"],
    status: "completed",
    dependencies: [],
    steps: [
      { title: "Charge marker", successCriteria: "10 marker-treat reps with eager orientation", sessionsRequired: 2, completedSessions: 2 },
      { title: "Use on eye contact", successCriteria: "Marks correct behavior within one second", sessionsRequired: 3, completedSessions: 3 },
    ],
    sources: [
      { title: "Clicker training basics", type: "article", url: "https://www.akc.org/expert-advice/training/clicker-training-your-dog-mark-and-reward/", publisher: "AKC" },
      { title: "Marker training explanation", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+marker+training+puppy", publisher: "Kikopup" },
      { title: "Positive reinforcement training", type: "article", url: "https://www.humanesociety.org/resources/positive-reinforcement-training", publisher: "Humane Society" },
    ],
    why: "A consistent marker lets every later skill become easier to teach and measure.",
  },
  {
    id: "sit",
    title: "Sit",
    track: "obedience",
    dogIds: ["puppy"],
    status: "current",
    dependencies: ["marker-word", "name-recognition"],
    steps: [
      { title: "Lure into sit", successCriteria: "Follows lure and sits 8 of 10 reps", sessionsRequired: 2, completedSessions: 2 },
      { title: "Fade food lure", successCriteria: "Responds to empty-hand cue 8 of 10 reps", sessionsRequired: 3, completedSessions: 1 },
      { title: "Add real-life cue", successCriteria: "Sits before bowl, door, or leash clip calmly", sessionsRequired: 4, completedSessions: 1 },
    ],
    sources: [
      { title: "Teach your puppy to sit", type: "article", url: "https://www.akc.org/expert-advice/training/how-to-teach-your-dog-to-sit/", publisher: "AKC" },
      { title: "Puppy sit training", type: "video", url: "https://www.youtube.com/results?search_query=zak+george+teach+puppy+sit", publisher: "Zak George" },
      { title: "Lure-and-reward training plan", type: "plan", url: "https://www.akc.org/expert-advice/training/lure-reward-training/", publisher: "AKC" },
    ],
    why: "Sit is partially unlocked: marker word is reliable, but name recognition needs one more calm session before the app advances sit to daily-life proofing.",
  },
  {
    id: "down",
    title: "Down",
    track: "obedience",
    dogIds: ["puppy"],
    status: "locked",
    dependencies: ["sit", "food-lure", "focus"],
    steps: [
      { title: "Lure elbows down", successCriteria: "Both elbows touch floor without pawing", sessionsRequired: 3, completedSessions: 1 },
      { title: "Hold down", successCriteria: "Maintains down for 10 seconds across 3 sessions", sessionsRequired: 3, completedSessions: 0 },
      { title: "Relaxed down", successCriteria: "Can down on mat after light play", sessionsRequired: 4, completedSessions: 0 },
    ],
    sources: [
      { title: "Teach down", type: "article", url: "https://www.akc.org/expert-advice/training/how-to-teach-your-dog-to-lie-down/", publisher: "AKC" },
      { title: "Train down without force", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+teach+dog+down", publisher: "Kikopup" },
      { title: "Basic commands owner's manual", type: "plan", url: "https://images.akc.org/pdf/ebook/Basic_Commands.pdf", publisher: "AKC" },
    ],
    why: "Needs sit, a reliable lure follow, and three short focus sessions before it becomes a primary task.",
  },
  {
    id: "leave-it",
    title: "Leave it",
    track: "obedience",
    dogIds: ["puppy", "griz"],
    status: "locked",
    dependencies: ["marker-word", "impulse-control", "drop-it"],
    steps: [
      { title: "Closed fist game", successCriteria: "Looks away from covered treat 8 of 10 reps", sessionsRequired: 3, completedSessions: 0 },
      { title: "Floor item", successCriteria: "Leaves visible item when cued with leash slack", sessionsRequired: 4, completedSessions: 0 },
      { title: "Real-world proofing", successCriteria: "Can pass low-value sidewalk items at 6 feet", sessionsRequired: 5, completedSessions: 0 },
    ],
    sources: [
      { title: "Teach leave it", type: "article", url: "https://www.akc.org/expert-advice/training/learning-the-leave-it-command/", publisher: "AKC" },
      { title: "Leave it step-by-step", type: "video", url: "https://www.youtube.com/results?search_query=dog+training+leave+it+positive+reinforcement", publisher: "YouTube training library" },
      { title: "Impulse control exercises", type: "plan", url: "https://www.whole-dog-journal.com/training/teaching-your-dog-self-control/", publisher: "Whole Dog Journal" },
    ],
    why: "Still locked because drop it has not started and impulse control is below the readiness threshold.",
  },
  {
    id: "loose-leash",
    title: "Loose leash walking",
    track: "obedience",
    dogIds: ["puppy", "griz"],
    status: "delayed",
    dependencies: ["sit", "recall-foundation", "outside-confidence"],
    ageGateWeeks: 14,
    steps: [
      { title: "Indoor leash pressure", successCriteria: "Turns toward handler when leash tightens", sessionsRequired: 3, completedSessions: 1 },
      { title: "Yard check-ins", successCriteria: "Offers 6 check-ins in a five-minute walk", sessionsRequired: 4, completedSessions: 1 },
      { title: "Quiet street", successCriteria: "Walks 30 feet with slack leash and two distractions", sessionsRequired: 5, completedSessions: 0 },
    ],
    sources: [
      { title: "Loose leash walking", type: "article", url: "https://www.akc.org/expert-advice/training/teach-puppy-walk-leash/", publisher: "AKC" },
      { title: "Loose leash training", type: "video", url: "https://www.youtube.com/results?search_query=kikopup+loose+leash+walking", publisher: "Kikopup" },
      { title: "Leash walking foundation", type: "plan", url: "https://www.sfspca.org/resource/loose-leash-walking/", publisher: "SF SPCA" },
    ],
    why: "Starts after recall foundation, outside confidence, and vaccine guidance line up. For now, the app schedules parallel decompression instead.",
  },
  {
    id: "dog-park",
    title: "Dog park readiness",
    track: "socialization",
    dogIds: ["puppy"],
    status: "locked",
    dependencies: ["vaccines-complete", "recall-foundation", "loose-leash", "dog-body-language"],
    ageGateWeeks: 24,
    steps: [
      { title: "Observe dogs at distance", successCriteria: "Relaxed body for 10 minutes at 50+ feet", sessionsRequired: 4, completedSessions: 0 },
      { title: "One known dog parallel walk", successCriteria: "Loose body and recovery after greetings", sessionsRequired: 4, completedSessions: 0 },
      { title: "Recall around dogs", successCriteria: "Responds 8 of 10 times around one calm dog", sessionsRequired: 6, completedSessions: 0 },
    ],
    sources: [
      { title: "Dog park safety", type: "article", url: "https://www.akc.org/expert-advice/lifestyle/dog-park-etiquette-tips/", publisher: "AKC" },
      { title: "Puppy socialization position statement", type: "plan", url: "https://avsab.org/resources/position-statements/", publisher: "AVSAB" },
      { title: "Reading dog body language", type: "video", url: "https://www.youtube.com/results?search_query=dog+body+language+play+signals+training", publisher: "YouTube behavior library" },
    ],
    why: "Dog park access requires vaccines, recall, loose leash skills, and consistently calm dog-to-dog body language.",
  },
];

export const healthEvents: HealthEvent[] = [
  { id: "vaccine-1", dogId: "puppy", title: "Puppy vaccine booster", date: "2026-07-15", kind: "vaccine", notes: "Confirm distemper/parvo schedule with vet." },
  { id: "heartworm", dogId: "griz", title: "Heartworm prevention", date: "2026-07-20", kind: "medication", notes: "Monthly prevention." },
  { id: "weight", dogId: "puppy", title: "Monthly weight", date: "2026-08-01", kind: "weight", notes: "Log growth and food adjustment." },
  { id: "groom", dogId: "griz", title: "Grooming reset", date: "2026-08-07", kind: "grooming", notes: "Brush, nail check, ear check." },
];

export const journalEntries: JournalEntry[] = [
  {
    id: "entry-1",
    dogIds: ["puppy", "griz"],
    date: "2026-07-09",
    title: "First parallel walk plan",
    text: "Keep both dogs moving in the same direction with enough distance that everyone can sniff and recover.",
    tags: ["relationship", "confidence", "walk"],
    mood: "steady",
  },
  {
    id: "entry-2",
    dogIds: ["puppy"],
    date: "2026-07-08",
    title: "Noise confidence baseline",
    text: "Puppy noticed the blender, recovered after food scatter, and chose to re-enter the kitchen.",
    tags: ["confidence", "noise", "kitchen"],
    mood: "great",
  },
];

export const feedbackLoopRules: FeedbackLoopRule[] = [
  {
    id: "task-completion",
    trigger: "Checkboxes, ratings, durations, accidents, barking, fear, guarding, and session counts",
    route: "algorithm",
    cadence: "instant",
    updates: [
      "Task streaks and overdue state",
      "Milestone step progress",
      "Readiness scores",
      "Tomorrow's optional workload",
      "Relationship and confidence trend lines",
    ],
    costControl: "Runs entirely in local code with no API call.",
  },
  {
    id: "health-records",
    trigger: "Vaccines, vet appointments, medications, weight entries, allergies, and insurance updates",
    route: "algorithm",
    cadence: "instant",
    updates: [
      "Static calendar",
      "Health alerts",
      "Age and vaccine gates",
      "Growth chart",
      "Blocked/unblocked health-dependent milestones",
    ],
    costControl: "Rules and date math handle the update; AI is only used for optional summarization of long vet notes.",
  },
  {
    id: "free-text-notes",
    trigger: "Journal text, task comments, copied vet instructions, or multi-day behavior descriptions",
    route: "genAI",
    cadence: "nightly",
    updates: [
      "Short trend summary",
      "Suggested tags",
      "Possible explanation for schedule changes",
      "Questions to ask the vet or trainer",
    ],
    costControl: "Batch once per day, summarize only new text, cap the prompt, and store the summary so it is not regenerated.",
  },
  {
    id: "weekly-review",
    trigger: "Seven days of structured logs or a manual weekly review request",
    route: "genAI",
    cadence: "weekly",
    updates: [
      "Weekly coaching note",
      "Plain-English explanation of adaptive changes",
      "Top three focus areas",
      "Suggested workload adjustment",
    ],
    costControl: "One compact request per week using rollups instead of raw history.",
  },
  {
    id: "safety-flags",
    trigger: "Bite, injury, severe fear, repeated guarding, medication reaction, or concerning vet note",
    route: "human-review",
    cadence: "instant",
    updates: [
      "Health or behavior alert",
      "Pause risky milestones",
      "Prompt to contact veterinarian or qualified trainer",
    ],
    costControl: "No model needed before the alert; AI can draft a summary for the professional only if requested.",
  },
  {
    id: "future-video",
    trigger: "Uploaded training or play video",
    route: "genAI",
    cadence: "on-demand",
    updates: [
      "Marker timing observation",
      "Engagement notes",
      "Body-language checklist",
      "Suggested next rep difficulty",
    ],
    costControl: "Never automatic. Run only on short clips selected by the user.",
  },
];
